export const courses = [
    'AN F211 Fluid Mechanics and Machines',
    'AN F221 Production Techniques',
    'AN F311 Principles of Aerodynamics',
    'AN F312 Aircraft Propulsion',
    'AN F313 Flight Mechanics and Controls',
    'AN F314 Introduction to Flight',
    'AN F315 Aircraft Structures',
    'AN F316 Orbital Mechanics',
    'AN F321 Aircraft Design',
    'AUE F211 Basic Design for Visualization',
    'AUE F212 Structural Mechanics',
    'AUE F213 Fluid Mechanics and Applications',
    'AUE F241 Architectural Design Studio I',
    'AUE F242 Building Construction & Technology',
    'AUE F243 Construction Economics',
    'AUE F266 Study Project',
    'AUE F311 Architectural Design Studio II',
    'AUE F312 Geotechnical Design',
    'AUE F313 Design of Reinforced Concrete Structures',
    'AUE F314 Highway Planning, Analysis and Design',
    'AUE F341 Urban Planning and Sustainable',
    'AUE F342 Building Acoustics and Lighting Design',
    'AUE F343 Design of Steel Structures',
    'AUE F344 Directed Research in Architecture – I',
    'AUE F345 Directed Research in Architecture – I',
    'AUE F361 Landscape Architecture',
    'AUE F362 Building Services',
    'AUE F366 Laboratory Project',
    'AUE F367 Laboratory Project',
    'AUE F376 Design Project',
    'AUE F377 Design Project',
    'AUE F421 Renewable Energy Systems in Buildings',
    'AUE F422 Urban Mass Transit Planning, Operations',
    'AUE F423 Machine Learning in Design Optimization',
    'AUE F424 Construction Management',
    'AUE F425 Building Information Modeling',
    'AUE F491 Special Project',
    'BBA F121 Business Ethics and Corporate Social',
    'BBA F122 Fundamentals of Business Statistics',
    'BBA F211 Financial and Management Accounting',
    'BBA F221 Human Resource Management',
    'BBA F222 Business Law and Compliance',
    'BBA F223 Optimization Techniques for Business',
    'BBA F266 Study Project',
    'BBA F311 Design Thinking',
    'BBA F321 Digital Enterprises',
    'BBA F341 Behavioural Finance',
    'BBA F342 Fintech',
    'BBA F343 Merger and Acquisition',
    'BBA F344 Marketing Channels',
    'BBA F345 Financial Analytics',
    'BBA F346 Marketing Research',
    'BBA F347 Marketing Analytics',
    'BBA F348 People Analytics',
    'BBA F349 Training and Development',
    'BBA F350 Performance Management',
    'BBA F351 Compensation Management',
    'BBA F352 Strategic Human Resource Management',
    'BBA F353 Organizational Change and Development',
    'BBA F354 Introduction to Consumer Behaviour',
    'BBA F355 International Marketing Strategies',
    'BBA F356 Predictive Analytics',
    'BBA F366 Laboratory Project',
    'BBA F367 Laboratory Project',
    'BBA F376 Design Project',
    'BBA F377 Design Project',
    'BBA F411 Forensic Accounting',
    'BBA F412 Islamic Finance',
    'BBA F413 Sales and Distribution Management',
    'BBA F414 Introduction to Service Marketing',
    'BBA F415 Customer Relationship Management',
    'BBA F416 Fundamental of Retailing',
    'BBA F417 Prescriptive Analytics',
    'BBA F418 Pricing Analytics',
    'BBA F419 Time Series Analysis and Forecasting',
    'BBA F420 Work, Health, and Safety',
    'BBA F421 Leadership Skills',
    'BBA F422 International Human Resource Management',
    'BBA F423 Talent Management and Development',
    'BBA F424 Strategic Leadership',
    'BBA F425 Introduction to Logistics Management',
    'BBA F491 Special Project',
    'BIO F101 Introduction to Biological Sciences',
    'BIO F110 Biology laboratory',
    'BIO F111 General Biology',
    'BIO F201 Introductory Biology',
    'BIO F211 Biological Chemistry',
    'BIO F212 Microbiology',
    'BIO F213 Cell Biology',
    'BIO F214 Integrated Biology',
    'BIO F215 Biophysics',
    'BIO F216 Water,Sanitation and Solid Waste Manage-',
    'BIO F217 Laboratory for Water,Sanitation and Solid',
    'BIO F231 Biology Project Laboratory',
    'BIO F241 Ecology and Environmental Sciences',
    'BIO F242 Introduction to Bioinformatics',
    'BIO F243 Genetics',
    'BIO F244 Instrumental Methods of Analysis',
    'BIO F266 Study Project',
    'BIO F311 Recombinant DNA Technology',
    'BIO F312 Plant Physiology',
    'BIO F313 Animal Physiology',
    'BIO F314 Conservation Biology',
    'BIO F315 Applied Nutrition and Nutraceuticals',
    'BIO F341 Developmental Biology',
    'BIO F342 Immunology',
    'BIO F352 Cell and Tissue Culture Technology',
    'BIO F366 Lab Project',
    'BIO F367 Lab Project',
    'BIO F376 Design Project',
    'BIO F377 Design Project',
    'BIO F411 Laboratory',
    'BIO F413 Molecular Biology of Cell',
    'BIO F417 Biomolecular Modelling',
    'BIO F418 Genetic Engineering Techniques',
    'BIO F419 Molecular Evolution',
    'BIO F421 Enzymology',
    'BIO F422 Fundamental of Tissue Engineering',
    'BIO F431 Reproductive Physiology',
    'BIO F441 Biochemical Engineering',
    'BIO F451 Bioprocess Technology',
    'BIO F491 Special Project',
    'BIO G510 Application of Computers and Statist ics in',
    'BIO G511 Population and Quantitative Genetics',
    'BIO G512 Molecular Mechanism of Gene Expression',
    'BIO G513 Microbial and Fermentation Technology',
    'BIO G514 Molecular Immunology',
    'BIO G515 Stem Cell and Regenerative Biology',
    'BIO G516 Fermentation Processes (5*)',
    'BIO G517 Recombinant DNA Technology',
    'BIO G522 Interferon Technology',
    'BIO G523 Advanced and Applied Microbiology',
    'BIO G524 Animal Cell Technology',
    'BIO G525 Environmental Biotechnology and Waste',
    'BIO G526 Cancer Biology',
    'BIO G528 Developmental Neuroscience',
    'BIO G532 Biostatistics and Biomodelling',
    'BIO G541 Neural Network Analysis',
    'BIO G542 Advanced Cell and Molecular Biology',
    'BIO G544 Bioremediation and Bio-metallurgy',
    'BIO G545 Molecular Parasitology & Vector Biology',
    'BIO G551 Membrane Biology',
    'BIO G561 Advances in Recombinant DNA Technology',
    'BIO G570 Recent Developments in Biology',
    'BIO G612 Human Genetics',
    'BIO G631 Membrane and Liposome Tech.',
    'BIO G632 Transgenic Technology',
    'BIO G641 Cell & Tissue Culture Technology',
    'BIO G642 Experimental Techniques',
    'BIO G643 Plant Biotechnology',
    'BIO G651 Protein and Enzyme Bioengineering',
    'BIO G661 Gene Toxicology',
    'BIO G671 Bioconversion Technology',
    'BIOT F211 Biological Chemistry',
    'BIOT F212 Microbiology',
    'BIOT F213 Cell Biology',
    'BIOT F215 Biophysics',
    'BIOT F241 Genetic Engineering Techniques',
    'BIOT F242 Introduction to Bioinformatics',
    'BIOT F243 Genetics',
    'BIOT F244 Instrumental Methods of Analysis',
    'BIOT F245 Introduction to Environmental',
    'BIOT F266 Study Project',
    'BIOT F311 Recombinant DNA Technology',
    'BIOT F314 Industrial Microbiology and Bio process',
    'BIOT F342 Immunology',
    'BIOT F343 Experiments in Biotechnology',
    'BIOT F344 Downstream Processing',
    'BIOT F345 Proteomics',
    'BIOT F346 Genomics',
    'BIOT F347 Immunotechnology',
    'BIOT F352 Cell and Tissue Culture Technology',
    'BIOT F366 Lab Project',
    'BIOT F367 Lab Project',
    'BIOT F376 Design Project',
    'BIOT F377 Design Project',
    'BIOT F413 Molecular Biology of the Cell',
    'BIOT F416 Introductio n to Pharmaceutical',
    'BIOT F417 Biomolecular Modeling',
    'BIOT F420 Introduction to Plant Biotechnology',
    'BIOT F422 Nanobiotechnology',
    'BIOT F423 Drug design and delivery',
    'BIOT F424 Food Biotechnology',
    'BIOT F491 Special Project',
    'BIOT F492 Applied Molecular Biology Project',
    'BITS F101 Social Conduct',
    'BITS F102 Innovation And Design Thinking',
    'BITS F111 Thermodynamics',
    'BITS F112 Technical Report Writing',
    'BITS F113 General Mathematics I',
    'BITS F114 General Mathematics II',
    'BITS F115 Introduction to Basic Sciences',
    'BITS F121 Introduction to Python',
    'BITS F122 Introduction to Spreadsheet Analysis',
    'BITS F123 Introduction to Engineering',
    'BITS F201 Material Science and Engineering',
    'BITS F211 Introduction to IPR',
    'BITS F212 Introduction to Human Rights',
    'BITS F213 Introduction to Environmental Studies',
    'BITS F214 Science, Technology and Modernity',
    'BITS F215 Applications of Bio -Medical Instrumenta-',
    'BITS F217 Environment, Developmen t and Climate',
    'BITS F218 General Mathematics III',
    'BITS F219 Process Engineering',
    'BITS F221 Practice School I',
    'BITS F225 Environmental Studies',
    'BITS F226 Soft Skills for Professionals',
    'BITS F231 Practice School I',
    'BITS F232 Foundations of Data Structures and Algo-',
    'BITS F233 Essentials of Start-up',
    'BITS F234 Introduction to Engineering Design',
    'BITS F235 Digital Fundamentals',
    'BITS F236 Foundation s of Artificial Intelligence for',
    'BITS F237 STEM for Sustainable Development',
    'BITS F238 Energy Literacy',
    'BITS F239 Evolution of Architecture',
    'BITS F240 Introduction to Environmental and Sus-',
    'BITS F241 Systems Engineering Principles',
    'BITS F311 Image Processing',
    'BITS F312 Neural Networks and Fuzzy Logic',
    'BITS F313 Multicriterion Decision Making in Engi-',
    'BITS F314 Game Theory and Its Applications',
    'BITS F315 Introduction to Cognitive Neuroscience',
    'BITS F316 Nonlinear Dynamics and Chaos',
    'BITS F317 Theoretical Neuroscience',
    'BITS F319 Negotiation Skills and Techniques',
    'BITS F320 Managerial Skills',
    'BITS F321 Legal and Economic Environment of Busi-',
    'BITS F322 Venture Team Development and Organiza-',
    'BITS F323 Venture Finance',
    'BITS F324 Strategy for Entrepreneurs',
    'BITS F325 New Product and Service Design',
    'BITS F326 Design Thinking for Innovation & Entrepre-',
    'BITS F327 Artificial Intelligence for Robotics',
    'BITS F328 Innovation Ecosystem and the Future of',
    'BITS F329 Social and Environmental Applications of',
    'BITS F330 Negotiation Skills and Techniques',
    'BITS F331 Quantum Computation and nformation I',
    'BITS F333 Project on Organisational Aspects',
    'BITS F334 Project on Organisational Aspects',
    'BITS F335 Discover Dubai',
    'BITS F335 Discover India',
    'BITS F343 Fuzzy Logic and Applications',
    'BITS F345 Information Law and Cyber Law',
    'BITS F351 Nonlinear Dynamics and Chaos',
    'BITS F364 Human Computer Interaction',
    'BITS F372 Data Communications and Networks',
    'BITS F381 TIC Projects',
    'BITS F382 Reading Course',
    'BITS F383 TIC Projects',
    'BITS F385 Introduction to Gender Studies',
    'BITS F386 Quantum Information and Computation',
    'BITS F398 Creative Multimedia',
    'BITS F399 Humanistic Theories of Science and Tech-',
    'BITS F407 Selected Readings',
    'BITS F412 Practice School II',
    'BITS F412 is a required course for all stude nts with Practice',
    'BITS F413 Practice School II',
    'BITS F414 Introduction to Bioinformatics',
    'BITS F415 Introduction to MEMS',
    'BITS F416 Introduction to Nanoscience',
    'BITS F417 Microfluidics and Its Application',
    'BITS F418 Introduction to Biomedical Engineering',
    'BITS F419 Management of Cross-cultural Engineering',
    'BITS F421 is a required course for all students with Thesis option',
    'BITS F421T Thesis',
    'BITS F422T Thesis',
    'BITS F423T Thesis',
    'BITS F424T Thesis',
    'BITS F425T Thesis',
    'BITS F425T and BITS F426T will be available only upon the spe-',
    'BITS F426T Thesis',
    'BITS F427 Digital Marketing',
    'BITS F428 Essentials of Strategic Management',
    'BITS F429 Nanotechnology for Renewable Energy',
    'BITS F430 Renewable Energy Laboratory',
    'BITS F431 Flexible Manufacturing Systems',
    'BITS F433 Supply Chain Analytics',
    'BITS F437 Technical Communication',
    'BITS F441 Robotics',
    'BITS F442 Remote Sensing and Image Processing',
    'BITS F444 Artificial Intelligence',
    'BITS F445 Neural Networks and Applications',
    'BITS F446 Pattern Recognition',
    'BITS F447 Multimedia Computing',
    'BITS F448 Retail Management Systems',
    'BITS F449 Financial Engineering',
    'BITS F451 Autonomous Mobile Robotics',
    'BITS F452 Blockchain Technology',
    'BITS F453 Computational Learning Theory',
    'BITS F454 Bio -Inspired Intelligence: Algorithms and',
    'BITS F455 Analytics For Supply Chain',
    'BITS F456 Capstone Project I',
    'BITS F457 Capstone Project II',
    'BITS F458 Professional Practice and Ethics',
    'BITS F459 Computer Vision',
    'BITS F461 Software Engineering',
    'BITS F462 Renewable Energy',
    'BITS F463 Cryptography',
    'BITS F464 Machine Learning',
    'BITS F465 Enterprise Computing',
    'BITS F466 Service Oriented Computing',
    'BITS F467 Bioethics and Biosafety',
    'BITS F468 New Venture Creation',
    'BITS F469 Financing Infrastructure Projects',
    'BITS F471 Introduction to Large Language Models',
    'BITS F474 Rural Infrastructure Planning',
    'BITS F482 Creating and Leading Entrepreneurial Or-',
    'BITS F488 Services Management Systems',
    'BITS F489 Enterprise Resource Planning',
    'BITS F493 Business Analysis and Valuation',
    'BITS F494 Environmental Impact Assessment',
    'BITS G501 Biostatistics',
    'BITS G511 Advanced Project',
    'BITS G512 Object Oriented Programming',
    'BITS G513 Study in Advanced Topics',
    'BITS G514 Environmental Health',
    'BITS G515 Management Principles and Practices',
    'BITS G516 Introduction to Business Sustainabiligy',
    'BITS G517 Cross Cultural Management',
    'BITS G518 Writing Seminar',
    'BITS G521 Fourth Generation Languages and',
    'BITS G522 Software Development Standards',
    'BITS G524 Health Economics and Policy I',
    'BITS G525 Health Economics and Policy II',
    'BITS G526 Data Sciences I',
    'BITS G527 Data Science II',
    'BITS G529 Research Project I',
    'BITS G533 Topics in Global Health I',
    'BITS G534 Topics in Global Health II',
    'BITS G539 Research Project II',
    'BITS G540 Research Practice',
    'BITS G541 User Interfaces',
    'BITS G553 Real Time Systems',
    'BITS G554 Data Compression',
    'BITS G560 Practice School',
    'BITS G561T Dissertation',
    'BITS G565T Dissertation',
    'BITS G612 Methods and Techniques of Systems Engi-',
    'BITS G613 Systems Analysis for Large Systems',
    'BITS G619 Professional Practice',
    'BITS G620 Professional Practice I',
    'BITS G621 Professional Practice II',
    'BITS G624 Computer Based Simulation and Modelling',
    'BITS G629T Dissertation',
    'BITS G630T Dissertation',
    'BITS G639 Practice School',
    'BITS G640 Practice School',
    'BITS G641 Management Information and Decisi on',
    'BITS G644 Development and Us e of Computer Soft-',
    'BITS G649 Reading Course',
    'BITS G651 Research based Capstone Project',
    'BITS G652 Industry based Capstone Project',
    'BITS G654 Advanced Instrumentation Tecniques',
    'BITS G659 Technical Communication',
    'BITS N101T Physical Fitness, Health and Wellness',
    'BITS N301T Personality Integration Leadership Orien-',
    'CAE F221 Façade Construction and Technology',
    'CAE F222 Integrated Building Façade Design',
    'CAE F223 Special Project on Façade Engineering',
    'CE F211 Mechanics of Solids',
    'CE F212 Transport Phenomena',
    'CE F213 Surveying',
    'CE F214 Construction Materials',
    'CE F230 Civil Engineering Materials',
    'CE F231 Fluid Mechanics',
    'CE F241 Analysis of Structures',
    'CE F242 Construction Planning and Technology',
    'CE F243 Soil Mechanics',
    'CE F244 Highway Engineering',
    'CE F266 Study Project',
    'CE F311 Design of Concrete Structures',
    'CE F312 Hydraulics Engineering',
    'CE F313 Foundation Engineering',
    'CE F320 Design of Reinforced Concrete Structures',
    'CE F321 Engineering Hydrology',
    'CE F323 Introduction to Environmental Engineering',
    'CE F324 Numerical Analysis',
    'CE F325 Fundamentals of Rock Mechanics',
    'CE F326 Impact of Climate Change on Water',
    'CE F331 In-situ Testing Methods in Geotechnical',
    'CE F341 Hydrology & Water Resources Engineering',
    'CE F342 Water & Waste Water Treatment',
    'CE F343 Design of Steel Structures',
    'CE F345 Computational Geomechanics',
    'CE F366 Lab Project',
    'CE F367 Lab Project',
    'CE F376 Design Project',
    'CE F377 Design Project',
    'CE F411 Operation Research for Engineers',
    'CE F412 Disaster Management',
    'CE F413 Advanced Structural Design',
    'CE F414 Introduction to Environmental Engineering',
    'CE F415 Design of Prestressed Concrete Structure',
    'CE F416 Computer Applications in Civil Engineering',
    'CE F417 Applications of Artificial Intelligence in Civil',
    'CE F419 Geotechnical Earthquake Engineering and',
    'CE F420 Introduction to Bridge Engineering',
    'CE F421 Analysis and Design of FRP Reinforced Con-',
    'CE F422 Urban Hydrology',
    'CE F423 Green Buildings and Energy Conservation',
    'CE F425 Airport, Railways and Waterways',
    'CE F426 Geosynthetics and Reinforced Soil Structure',
    'CE F427 System Modeling and Analysis',
    'CE F428 Earthquake Resistant Design and',
    'CE F429 Design of Foundation Systems',
    'CE F430 Design of Advanced Concrete Structures',
    'CE F431 Principles of Geographical Information',
    'CE F432 Structural Dynamics',
    'CE F433 Remote Sensing and Image Processing',
    'CE F434 Environmental Impact Assessment',
    'CE F435 Introduction to Finite Element Methods',
    'CE F491 Special Project',
    'CE G511 Matrix Methods in Civil Engineering',
    'CE G512 Topics in Environmental Engineering',
    'CE G513 Advanced Computational Techniques',
    'CE G514 Structural Optimization',
    'CE G515 Fundamentals of Systems Engineering',
    'CE G516 Multicriteria Analysis in Engineering',
    'CE G517 Waste Management Systems',
    'CE G518 Pavement Analysis and Design',
    'CE G520 Infrastructure Planning and Management',
    'CE G521 Topics in Structural Engineering',
    'CE G522 Pavement Design, Maintenance and Manage-',
    'CE G523 Transportation Systems Planning and Man-',
    'CE G524 Urban Mass Transit Planning, Operations and',
    'CE G525 Water Resources Planning and Management',
    'CE G526 Systems Approach to Water Resources',
    'CE G527 Construction Management',
    'CE G528 Selection of Construction Equipment and',
    'CE G529 Construction Project Control Systems',
    'CE G530 Design of Construction Operations',
    'CE G531 Environmental Conservation',
    'CE G532 Advanced Soil Mechanics',
    'CE G533 Advanced Composite Materials for',
    'CE G534 Pavement Material Characterization',
    'CE G535 Highway Geometric Design',
    'CE G536 Traffic Engineering and Safety',
    'CE G537 Transportation Economics and Finance',
    'CE G538 Project Planning and Management',
    'CE G539 Introduction to Discrete Choice Theory',
    'CE G542 Water Resources and Management',
    'CE G543 Traffic Flow Theory',
    'CE G544 Fracture Mechanics of Concrete Structures',
    'CE G545 Airport Planning and Design',
    'CE G546 Highway Construction Practices',
    'CE G547 Pavement Failures, Evaluation and Rehabili-',
    'CE G548 Pavement Management Systems',
    'CE G549 Rural Road Technology',
    'CE G551 Dynamics of structures',
    'CE G552 Advanced Structural Mechanics and Sta-',
    'CE G553 Theory of Plates and Shells',
    'CE G554 Advanced Structural Design',
    'CE G555 Remote Sensing and GIS in Water Resources',
    'CE G556 Advanced Computational Hydraulics',
    'CE G557 Stochastic Hydrology',
    'CE G558 Advanced Groundwater Hydrology',
    'CE G559 Soft Computing in Water Resources',
    'CE G560 Hydrologic Simulation Laboratory',
    'CE G561 Impact of Clim ate Change on Water',
    'CE G562 Advanced Concrete Technology',
    'CE G563 Stochastic Methods in Civil Engineering',
    'CE G564 Structural Health Assessment and',
    'CE G565 Transportation Planning',
    'CE G566 Public Transportation',
    'CE G567 Highway Design',
    'CE G568 Traffic Systems Analysis',
    'CE G569 Transportation Economics',
    'CE G570 Highway Construction Technology',
    'CE G571 Road Asset Management',
    'CE G572 Transportation Data Analytics',
    'CE G573 Road Safety and Accident Analysis',
    'CE G574 Pavement Maintenance',
    'CE G575 Freight Transportation',
    'CE G576 Advanced Computational Modelling',
    'CE G577 Impact of Climate Change on Structural',
    'CE G610 Computer Aided Analysis and Design in Civil',
    'CE G611 Computer Aided Analysis and Design',
    'CE G612 Advanced steel Structures',
    'CE G613 Advanced concrete Structures',
    'CE G614 Prestressed Concrete Structures',
    'CE G615 Earthquake Engineering',
    'CE G616 Bridge Engineering',
    'CE G617 Advanced Structural Analysis',
    'CE G618 Design of Multi-Storey Structures',
    'CE G619 Finite element analysis',
    'CE G620 Advanced Foundation Engineering',
    'CE G621 Fluid Dynamics',
    'CE G622 Soil-Structure-Interaction',
    'CE G623 Ground Improvement Techniques',
    'CE G631 Selecte d Topics in Soil Mechanics and Ge-',
    'CE G632 Design of Foundations for Dynamic Loads',
    'CE G641 Theory of Elasticity and Plasticity',
    'CHE F211 Chemical Process Calculations',
    'CHE F212 Fluid Mechanics',
    'CHE F213 Chemical Engineering Thermodynamics',
    'CHE F214 Engineering Chemistry',
    'CHE F241 Heat Transfer',
    'CHE F242 Numerical Methods for Chemical Engineers',
    'CHE F243 Material Science and Engineering',
    'CHE F244 Separation Processes I',
    'CHE F266 Study Project',
    'CHE F311 Kinetics and Reactor Design',
    'CHE F312 Chemical Engineering Lab I',
    'CHE F313 Separation Processes II',
    'CHE F314 Process Design Principles I',
    'CHE F315 Machine Learning for Chemical Engineers',
    'CHE F316 Sustainable Energy Systems',
    'CHE F317 Energy Systems Engineering',
    'CHE F341 Chemical Engineering Laboratory II',
    'CHE F342 Process Dynamics and Control',
    'CHE F343 Process Design Principles II',
    'CHE F366 Lab Project',
    'CHE F367 Lab Project',
    'CHE F376 Design Project',
    'CHE F377 Design Project',
    'CHE F411 Environmental Pollution Control',
    'CHE F412 Process Equipment Design',
    'CHE F413 Process Plant Safety',
    'CHE F414 Transport Phenomena',
    'CHE F415 Molecular and Statistical Thermodynamics',
    'CHE F416 Process Plant Design Project I',
    'CHE F417 Process Plant Design Project II',
    'CHE F418 Modelling and Simulation in Chemical Engi-',
    'CHE F419 Chemical Process Technology',
    'CHE F421 Biochemical Engineering',
    'CHE F422 Petroleum Refining Technology',
    'CHE F423 Membrane Science and Engineering',
    'CHE F424 Rheology of complex fluids',
    'CHE F425 Environmental Management Systems',
    'CHE F433 Corrosion Engineering',
    'CHE F471 Advanced Process Control',
    'CHE F491 Special Project',
    'CHE F497 Atomic and Molecular Simulations',
    'CHE F498 Colloids and Interface Engineering',
    'CHE G511 Fluidisation Engineering',
    'CHE G512 Petroleum Refining and Petro- Chemicals',
    'CHE G513 Environmental Management Systems',
    'CHE G514 Evolutionary Computation',
    'CHE G521 Chemical Engineering Analysis',
    'CHE G522 Polymer Technology',
    'CHE G523 Mathematical Methods in Chemical',
    'CHE G524 Introduction to Multiphase Flow',
    'CHE G525 Chemical Process and Equipment Design',
    'CHE G526 Nuclear Engineering',
    'CHE G527 Energy Conservation and Management',
    'CHE G528 Introduction to Nano Science and',
    'CHE G529 Pulp and Paper Technology',
    'CHE G531 Project Engineering',
    'CHE G532 Alternate Energy Resources',
    'CHE G533 Petroleum Product Characterization',
    'CHE G541 Process Plant Simulation',
    'CHE G542 Computational Transport Phenomena',
    'CHE G551 Advanced Separation Technology',
    'CHE G552 Advanced Transport Phenomena',
    'CHE G553 Statistical Thermodynamics',
    'CHE G554 Computational Fluid Dynamics',
    'CHE G556 Electrochemical Engineering',
    'CHE G557 Energy Systems Engineering',
    'CHE G558 Chemical Process Optimization',
    'CHE G559 Reactor Physics and Engineering',
    'CHE G560 Nuclear Fuel Cycle and Waste Management',
    'CHE G561 Nuclear Reactor Control and Instrumenta-',
    'CHE G562 Thermal Hydraulics and Heat Transfer',
    'CHE G563 Nuclear Chemical Engineering',
    'CHE G564 Nuclear Materials and Radiation Damage',
    'CHE G565 Radiation and Radio Isotopes Applications',
    'CHE G566 Nuclear Safety, Security and Safeguards',
    'CHE G567 Natural Gas Processing',
    'CHE G568 Modeling and Simulation in Petroleum',
    'CHE G569 Petroleum Production Economics',
    'CHE G611 Computer Aided Analysis and Design',
    'CHE G613 Advanced Mass Transfer',
    'CHE G614 Advanced Heat Transfer',
    'CHE G615 Advanced Separation Processes',
    'CHE G616 Petroleum Reservoir Engineering',
    'CHE G617 Petroleum Refinery Engineering',
    'CHE G618 Petroleum Downstream Processing',
    'CHE G619 Process Intensification',
    'CHE G620 Energy Integration Analysis',
    'CHE G621 Fluid Dynamics',
    'CHE G622 Advanced Chemical Engineering Thermody-',
    'CHE G641 Reaction Engineering',
    'CHEM F101 Fundamentals of Chemistry',
    'CHEM F110 Chemistry Laboratory',
    'CHEM F111 General Chemistry',
    'CHEM F211 Physical Chemistry I',
    'CHEM F212 Organic Chemistry I',
    'CHEM F213 Physical Chemistry II',
    'CHEM F214 Inorganic Chemistry I',
    'CHEM F223 Colloid and Surface Chemistry',
    'CHEM F241 Inorganic Chemistry II',
    'CHEM F242 Chemical Experimentation I',
    'CHEM F243 Organic Chemistry II',
    'CHEM F244 Physical Chemistry III',
    'CHEM F266 Study Project',
    'CHEM F311 Organic Chemistry III',
    'CHEM F312 Physical Chemistry IV',
    'CHEM F313 Instrumental Methods of Analysis',
    'CHEM F320 Introductory Computational Chemistry La-',
    'CHEM F323 Biophysical Chemistry',
    'CHEM F324 Numerical Methods in Chemistry',
    'CHEM F325 Polymer Chemistry',
    'CHEM F326 Solid State Chemistry',
    'CHEM F327 Electrochemistry: Fundamentals and',
    'CHEM F328 Supramolecular Chemistry',
    'CHEM F329 Analytical Chemistry',
    'CHEM F330 Photophysical Chemistry',
    'CHEM F333 Chemistry of Materials',
    'CHEM F334 Magnetic Resonance',
    'CHEM F335 Organic Chemistry and Drug Design',
    'CHEM F336 Nanochemistry',
    'CHEM F337 Green Chemistry and Catalysis',
    'CHEM F341 Chemical Experimentation II',
    'CHEM F342 Organic Chemistry IV',
    'CHEM F343 Inorganic Chemistry III',
    'CHEM F366 Lab Project',
    'CHEM F367 Lab Project',
    'CHEM F376 Design Project',
    'CHEM F377 Design Project',
    'CHEM F412 Photochemistry and Laser Spectroscopy',
    'CHEM F413 Electron Correlation in Atoms and Mole-',
    'CHEM F414 Bio and Chemical Sensors',
    'CHEM F415 Frontiers in Organic Synthesis',
    'CHEM F416 Applied Crystallography',
    'CHEM F422 Statistical Thermodynamics',
    'CHEM F423 Astrochemistry',
    'CHEM F430 Atmospheric Chemistry',
    'CHEM F431Sustainable Chemistry using Renewables',
    'CHEM F491 Special Project',
    'CHEM G511 Nuclear and Radio Chemistry',
    'CHEM G513 Advanced Nuclear and Radio-chemistry',
    'CHEM G521 Environmental Chemistry',
    'CHEM G531 Recent Advances in Chemistry',
    'CHEM G541 Chemical Applications of Group Theory',
    'CHEM G551 Advanced Organic Chemistry',
    'CHEM G552 Advanced Inorganic Chemistry',
    'CHEM G553 Advanced Physical Chemistry',
    'CHEM G554 Physical Methods in Chemistry',
    'CHEM G555 Chemistry of Life Processes',
    'CHEM G556 Catalysis',
    'CHEM G557 Solid Phase Synthesis and Combinatorial',
    'CHEM G558 Electronic Structure Theory',
    'CHEM G559 Bioinorganic Chemistry',
    'CHEM G561 Heterocyclic Chemistry',
    'CHEM G562 Solid State Chemistry',
    'CHEM G563 Advanced Statistical Mechanics',
    'CHI N101T Beginning Chinese',
    'CS F111 Computer Programming',
    'CS F211 Data Structures & Algorithms',
    'CS F212 Database Systems',
    'CS F213 Object Oriented Programming',
    'CS F214 Logic in Computer Science',
    'CS F215 Digital Design',
    'CS F222 Discrete structures for Computer Science',
    'CS F241 Microprocessors & Interfacing',
    'CS F266 Study Project',
    'CS F301 Principles of Programming Languages',
    'CS F303 Computer Networks',
    'CS F314 Software Development for Portable Devices',
    'CS F315 Information and Communication Techno lo-',
    'CS F316 Quantum Architecture and Programming',
    'CS F317 Reinforcement Learning',
    'CS F320 Foundations of Data Science',
    'CS F321 System Security',
    'CS F322 Knowledge Graphs -Foundations and',
    'CS F342 Computer Architecture',
    'CS F351 Theory of Computation',
    'CS F362 Programming Languages and Compiler',
    'CS F363 Compiler Construction',
    'CS F364 Design and Analysis of Algorithms',
    'CS F366 Lab Project',
    'CS F367 Lab Project',
    'CS F372 Operating Systems',
    'CS F376 Design Project',
    'CS F377 Design Project',
    'CS F401 Multimedia Computing',
    'CS F402 Computational Geometry',
    'CS F404 Computer Crime and Forensics',
    'CS F406 Ethical Hacking',
    'CS F407 Artificial Intelligence',
    'CS F413 Internetworking Technologies',
    'CS F415 Data Mining',
    'CS F422 Parallel Computing',
    'CS F424 Software for Embedded Systems',
    'CS F425 Deep Learning',
    'CS F426 Graph Mining',
    'CS F427 Performance Analysis of Computer Networks',
    'CS F428 Special Topic in Computer Science',
    'CS F429 Natural Language Processing',
    'CS F430 Approximation Algorithms',
    'CS F431 Combinatorial Optimization',
    'CS F432 Brain-inspired Deep Learning',
    'CS F433 Computational Neuroscience',
    'CS F434 Data science for Healthcare',
    'CS F435 Cyber Security Analytics and Forensics',
    'CS F436 Cyber Physical Systems and Security',
    'CS F437 Generative Artificial Intelligence',
    'CS F441 Selected Topics from Computer Science',
    'CS F444 Real–Time Systems',
    'CS F446 Data Storage Technologies and Networks',
    'CS F451 Combinatorial Mathematics',
    'CS F468 Information Security Project',
    'CS F469 Information Retrieval',
    'CS F491 Special Project',
    'CS G501 Mobile Computing',
    'CS G511 Design and Analysis of Algorithms',
    'CS G512 Introduction to Authoring Systems',
    'CS G513 Network Security',
    'CS G514 Object Oriented Analysis and Design',
    'CS G515 Queueing Systems Theory',
    'CS G516 Advanced Database Systems',
    'CS G517 Network and System Security',
    'CS G518 Internet of Things: Design and Development',
    'CS G519 Social Media Analytics',
    'CS G520 Advanced Data Mining',
    'CS G521 Object Oriented Programming',
    'CS G523 Software for Embedded Systems',
    'CS G524 Advanced Computer Architecture',
    'CS G525 Advanced Computer Networks',
    'CS G526 Advanced Algorithms & Complexity',
    'CS G527 Cloud Computing',
    'CS G531 Testable Design & Fault Tolerant Computing',
    'CS G532 High Performance Heterogeneous',
    'CS G533 Software Engineering for Machine-Learned',
    'CS G534 Automotive Security',
    'CS G541 Pervasive Computing',
    'CS G551 Advanced Compilation Techniques',
    'CS G553 Reconfigurable Computing',
    'CS G554 Distributed Data Systems',
    'CS G555 System Specifications and Modelling',
    'CS G557 Distributed Computing',
    'CS G559 Database Security',
    'CS G562 Advanced Architecture and Perfo rmance',
    'CS G564 Advanced Cryptography',
    'CS G566 Secure Software Engineering',
    'CS G568 Network Security Project',
    'CS G611 Distributed Processing Systems',
    'CS G612 Fault Tolerant System Design',
    'CS G622 Local Area Networks: Design and Implemen-',
    'CS G623 Advanced Operating Systems',
    'CS G631 Devices, Data Communications and Control',
    'CS G632 Application Driven System Design',
    'CS G641 Microprocessor-Based Systems Design',
    'CS G642 Recent Advances in Computing',
    'CS G651 Symbolic Computing & Computer Algebra',
    'CS G652 Digital Communications and Message',
    'CS G653 Software Architectures',
    'CS G671 Advanced Computer Graphics',
    'DE G511 Advanced Methods in Applied A Mathematics',
    'DE G512 Finite Element Analysis',
    'DE G513 Tribiology',
    'DE G514 Fracture Mechanics',
    'DE G521 Instrumentation and Applied Electronics',
    'DE G522 Design Projects',
    'DE G531 Product Design',
    'DE G532 Quality Assurance & Reliability',
    'DE G611 Dynamics & Vibrations',
    'DE G621 Digital & Microprocessor Based Systems',
    'DE G631 Materials Technology & Testing',
    'ECE F211 Electrical Machines',
    'ECE F212 Electromagnetic Theory',
    'ECE F214 Electronic Devices',
    'ECE F215 Digital Design',
    'ECE F216 Electronic Devices Simulation Laboratory',
    'ECE F241 Microprocessors and interfacing',
    'ECE F242 Control Systems',
    'ECE F243 Signals and Systems',
    'ECE F244 Microelectronic Circuits',
    'ECE F266 Study Project',
    'ECE F311 Communication Systems',
    'ECE F312 EM Fields and Microwave Engineering La-',
    'ECE F314 Electromagnetic Fields and Microwave Engi-',
    'ECE F331 Microwave Engineering',
    'ECE F341 Analog Electronics',
    'ECE F343 Communication Networks',
    'ECE F344 Information Theory and Coding',
    'ECE F366 Lab Project',
    'ECE F367 Lab Project',
    'ECE F376 Design Project',
    'ECE F377 Design Project',
    'ECE F414 : Telecommunication Switching Systems and Net-',
    'ECE F414 Telecommunication Switching Systems and',
    'ECE F416 Digital Communication',
    'ECE F418 Modern Communication Technologies',
    'ECE F423 Electronic Material Design and Simulations',
    'ECE F424 Smart Grid for Sustainable Energy',
    'ECE F428 Energy Storage Systems',
    'ECE F431 Mobile Telecommunication Networks',
    'ECE F434 Digital Signal Processing',
    'ECE F438 Electric Vehicles',
    'ECE F472 Satellite Communication',
    'ECE F491 Special Project',
    'ECOM F211 Data Structures & Algorithms',
    'ECOM F213 Object Oriented Programming',
    'ECOM F214 Electronic Devices',
    'ECOM F215 Digital Design',
    'ECOM F222 Discrete Structures for Computer Science',
    'ECOM F241 Microprocessors and Interfacing',
    'ECOM F242 Control Systems',
    'ECOM F243 Signals and Systems',
    'ECOM F244 Microelectronic Circuits',
    'ECOM F266 Study Project',
    'ECOM F313 Analog & Digital VLSI Design',
    'ECOM F321 Real Time Operating Systems',
    'ECOM F342 Computer Architecture',
    'ECOM F343 Communication Networks',
    'ECOM F366 Lab Project',
    'ECOM F376 Design Project',
    'ECOM F377 Design Project',
    'ECOM F462 Network Programming',
    'ECOM F491 Special Project',
    'ECON F211 Principles of Economics',
    'ECON F212 Fundamentals of Finance and Accounts',
    'ECON F213 Mathematical & Statistical Methods',
    'ECON F214 Economic Environment of Business',
    'ECON F215 Computational Methods for Economics',
    'ECON F241 Econometric Methods',
    'ECON F242 Microeconomics',
    'ECON F243 Macroeconomics',
    'ECON F244 Economics of Growth and Development',
    'ECON F266 Study Project',
    'ECON F311 International Economics',
    'ECON F312 Money, Banking and Financial Markets',
    'ECON F313 Issues in Economic Development',
    'ECON F314 Industrial Economics',
    'ECON F341 Public Finance Theory and Policy',
    'ECON F342 Applied Econometrics',
    'ECON F343 Economic Analysis of Public Policy',
    'ECON F344 Models in Operations Management',
    'ECON F345 Behavioral Economics',
    'ECON F351 Indian Economic Development',
    'ECON F352 Management of Banks and Financial',
    'ECON F353 Energy Economics and Policy',
    'ECON F354 Derivatives and Risk Management',
    'ECON F355 Business Analysis and Valuation',
    'ECON F356 Strategic Financial Management',
    'ECON F357 Management Control System',
    'ECON F366 Lab Project',
    'ECON F367 Lab Project',
    'ECON F376 Design Project',
    'ECON F377 Design Project',
    'ECON F411 Project Appraisal',
    'ECON F412 S ecurity Analysis and Portfolio',
    'ECON F413 Financial Engineering',
    'ECON F414 Creating and Leading Ent repreneurial',
    'ECON F415 New Venture Creation',
    'ECON F416 Regional Economics',
    'ECON F418 Quantitative Analysis of International',
    'ECON F419 Advanced Microeconomics',
    'ECON F420 Applied Macroeconometrics',
    'ECON F422 Functions and Working of Stock',
    'ECON F471 Resources and Environmental Economics',
    'ECON F491 Special Projects',
    'ECON G511 Dynamic Modeling and Control of National',
    'ECON G521 Modern Cost Engineering',
    'ECON G531 Theory of Macroeconomic Policy',
    'ECON G541 Economic Systems Analysis',
    'ECON G542 Accounting Theory and Empirical',
    'ECON G543 Advanced Corporate Finance',
    'ECON G544 Empirical Asset Pricing',
    'ECON G545 Financial Economics',
    'ECON G546 Topics in Econometrics',
    'ECON G547 Topics in Macroeconomics',
    'ECON G548 Topics in Mathematical Economics',
    'ECON G549 Topics in Microeconomics',
    'EE G501 Environmental Sampling and Analytical',
    'EE G502 Water and Wastewater Treatment Systems',
    'EE G503 Environmental Systems Modelling',
    'EE G504 Physico Chemical Treatment Principles and',
    'EE G505 Biological Treatment Principles and Design of',
    'EE G506 Environmental Statistics',
    'EE G507 Industrial Pollution Abatement',
    'EE G508 Urban Water Management',
    'EE G601 Energy Generation and Management in Waste',
    'EE G602 Environmental Remote Sensing and GIS',
    'EE G603 Air Pollution Control Technologies',
    'EE G604 Solid Waste Management',
    'EE G605 Environmental Process Engineering',
    'EE G606 Environmental Impact and Risk Assessment',
    'EEE F111 Electrical Sciences',
    'EEE F211 Electrical Machines',
    'EEE F212 Electromagnetic Theory',
    'EEE F214 / INSTR F214 / ECE F214 : Electronic Devices',
    'EEE F214 Electronic Devices',
    'EEE F215 Digital Design',
    'EEE F216 Electronic Devices Simulation Laboratory',
    'EEE F241 Microprocessors and Interfacing',
    'EEE F242 / INSTR F242 / ECE F242 : Control Systems',
    'EEE F242 Control Systems',
    'EEE F243 Signals & Systems',
    'EEE F244 Microelectronic Circuits',
    'EEE F245 Control System Laboratory',
    'EEE F246 Electrical and Electronic Circuits Labora-',
    'EEE F266 Study Project',
    'EEE F311 Communication Systems',
    'EEE F312 Power Systems',
    'EEE F313 Analog & Digital VLSI Design',
    'EEE F314 FPGA Based System Design',
    'EEE F341 Analog Electronics',
    'EEE F342 Power Electronics',
    'EEE F345 Power Apparatus & Networks',
    'EEE F346 Data Communication Networks',
    'EEE F347 Communication Networks Laboratory',
    'EEE F348 FPGA Based System Design Laboratory',
    'EEE F366 Lab Project',
    'EEE F367 Lab Project',
    'EEE F376 Design Project',
    'EEE F377 Design Project',
    'EEE F411 Internet of Things',
    'EEE F414 Telecommunication Switching Systems &',
    'EEE F416 Digital Communication',
    'EEE F417 Computer Based Control Systems',
    'EEE F418 Modern Communication Technologies',
    'EEE F419 Flexible and Stretchable Electronics',
    'EEE F420 Biomedical Signal Processing',
    'EEE F422 Modern Control Systems',
    'EEE F423 Electronic Material Design and Simulations',
    'EEE F424 Smart Grid for Sustainable Energy',
    'EEE F425 Power System Analysis and Control',
    'EEE F426 Fiber Optics & Optoelectronics',
    'EEE F427 Electric Power Utilization and Illumination',
    'EEE F428 Energy Storage Systems',
    'EEE F429 Smart Materials and Applications',
    'EEE F430 Green Communications and Networks',
    'EEE F431 Mobile Telecommunication Networks',
    'EEE F432 Medical Instrumentation',
    'EEE F433 Electromagnetic Fields & Waves',
    'EEE F434 Digital Signal Processing',
    'EEE F435 Digital Image Processing',
    'EEE F436 Electromagnetic Compatibility',
    'EEE F437 Semiconductor Fabrication Technology',
    'EEE F438 Electric Vehicles',
    'EEE F439 Communication and Computing for Drones',
    'EEE F462 Advanced Power Systems',
    'EEE F472 Satellite Communication',
    'EEE F473 Wind Electrical Systems',
    'EEE F474 Antenna Theory and Design',
    'EEE F475 Special Electrical Machines',
    'EEE F476 Switchgear and Protection',
    'EEE F477 Modeling of Field-Effect NanoDevices',
    'EEE F478 Power Systems Laboratory',
    'EEE F491 Special Projects',
    'EEE G510 RF Microelectronics',
    'EEE G511 RF and Microwave Circuit Design',
    'EEE G512 Embedded System Design',
    'EEE G513 Machine Learning for Electronics Engineers',
    'EEE G514 Nanoelectronic Memories and Technology',
    'EEE G515 Real Time Embedded Systems',
    'EEE G516 Signal Theory and Optimization',
    'EEE G520 Wireless and Mobile Communication',
    'EEE G521 Optoelectronic Devices, Circuits &Systems',
    'EEE G522 Advanced Satellite Communication',
    'EEE G523 Processor Architecture and Design',
    'EEE G524 VLSI Architectural Design and Implementation',
    'EEE G525 Wireless Communication Systems',
    'EEE G526 Lightwave Engineering',
    'EEE G531 Testable Design and Fault Tolerant',
    'EEE G532 Embedded Systems Testing and Debugging',
    'EEE G533 Embedded Middleware Design',
    'EEE G534 Cloud, Fog and Edge Computing',
    'EEE G535 Sensors, Actuators and signal conditioning',
    'EEE G536 Automotive Embedded Systems',
    'EEE G537 Embedded System for Robotics',
    'EEE G538 Storage Technologies and Networks',
    'EEE G539 Modelling and Analysis of Electrical Machines',
    'EEE G540 Advanced Control Techniques for Power',
    'EEE G541 Distribution Apparatus and Configurations',
    'EEE G542 Power Electronic Converters',
    'EEE G543 Power Device Microelectronics and',
    'EEE G544 Steady State and Dynamics of Electric',
    'EEE G545 Control and Instrumentation for Power',
    'EEE G546 Systems Simulation Lab.',
    'EEE G547 Device Drivers',
    'EEE G548 Distributed and Networked Embedded Systems',
    'EEE G551 Digital Signal Processing for Embedded',
    'EEE G552 Solid State Drives',
    'EEE G553 Utility Applications of Power Electronics',
    'EEE G554 Soft Switching Converter Technologies',
    'EEE G555 Transformer and Motor Design',
    'EEE G556 DSP Based Control of Electric Drives',
    'EEE G557 Drives for Electronic Transaction',
    'EEE G558 DSP Based Implementation Drivers',
    'EEE G559 Advanced Power Electronics',
    'EEE G561 Augmented and Virtual Reality',
    'EEE G562 Computer Vision for Embedded Systems',
    'EEE G581 RF & Microwave Engineering',
    'EEE G582 Telecom Network Management',
    'EEE G591 Optical Communication',
    'EEE G592 Mobile & Personal Communication',
    'EEE G593 Power Quality',
    'EEE G594 Advanced VLSI Devices',
    'EEE G595 Nanoelec tronics and Nanophotonics',
    'EEE G596 Renewable Energy Integration to Grid',
    'EEE G611 Computer Aided Analysis and Design',
    'EEE G612 Coding Theory & Practice',
    'EEE G613 Advanced Digital Signal Processing',
    'EEE G614 Advanced Wireless Communications',
    'EEE G621 Advanced Electronic Circuits',
    'EEE G622 Advanced Digital Communication',
    'EEE G623 Embedded Network Security',
    'EEE G625 Safety Critical Embedded Systems Design',
    'EEE G626 Hardware Software Co-Design',
    'EEE G627 Network Embedded Applications',
    'EEE G628 Intelligent Mechatronic Systems',
    'EEE G629 Advanced Design Project',
    'EEE G631 Accelerated Embedded Systems',
    'EEE G632 Big Data Analytics on End and Edge',
    'EEE G633 System on Chip',
    'EEE G634 Avionics Systems',
    'EEE G641Applied Estimation Theory',
    'ENGL G511 Growth of the English Language',
    'ENGL G512 Language and S & T',
    'ENGL G513 Social Impact of S&T',
    'ENGL G521 Principles of Language Teaching',
    'ENGL G522 Aesthetics and Technology',
    'ENGL G531 Applied Linguistics',
    'ENGL G541 Interpretation of Literature',
    'ENGL G551 Information Technology Lab I',
    'ENGL G561 Information Technology Lab II',
    'ENGL G571 Applied Communication I',
    'ENGL G581 Applied Communication II',
    'ENGL G591 Project Formulation and Preparation',
    'ENGL G611 Twentieth Century English Literature',
    'ENV F212 Environmental Chemistry and',
    'ENV F222 Transport Phenomena for',
    'ENVS F211 Hydraulics and Fluid Mechanics',
    'ENVS F213 Water and Wastewater Treatment',
    'ENVS F223 Material Science and Engineering',
    'ENVS F224 Sampling and Analytical Techniques',
    'ENVS F311 Environmental Modelling',
    'ENVS F312 Air Pollution Control',
    'ENVS F313 Digital Sustainability',
    'ENVS F314 Environmental Engineering Lab',
    'ENVS F321 Sustainability Policies and Measures',
    'ENVS F322 Solid Waste Management',
    'ENVS F323 Sustainable Urban Design and',
    'ENVS F324 Environmental Economics and',
    'ENVS F331 Climate Change Adaptation and',
    'ENVS F332 Energy Transition and Storage',
    'ENVS F333 Environmental Sustainability Ventures',
    'FIN F212 Fundamentals of Finance and Accounts',
    'FIN F213 Mathematical and Statistical Methods',
    'FIN F214 Economic Environment of Business',
    'FIN F242 Introduction to Financial Mathematics',
    'FIN F243 Functions and Working of Stock Exchanges',
    'FIN F244 Indian Financial System',
    'FIN F266 Study Project',
    'FIN F311 Derivatives & Risk Management',
    'FIN F312 Fundamental of Taxation & Audit',
    'FIN F313 Security Analysis and PortfolioManagement',
    'FIN F314 Investment Banking and Financial Services',
    'FIN F315 Financial Management',
    'FIN F341 International Financial Markets and Services',
    'FIN F342 Project Finance',
    'FIN F366 Lab Project',
    'FIN F367 Lab Project',
    'FIN F414 Financial Risk Analytics and Management',
    'FIN F491 Special Project',
    'FRE N101T Beginning French',
    'FRE N102T Technical French',
    'GER N101T Beginning German',
    'GER N102T Technical German',
    'GS F211 Modern Political Concepts',
    'GS F212 Environment, Development & Climate Change',
    'GS F213 Development Theories',
    'GS F221 Business Communication',
    'GS F222 Language Lab Practice',
    'GS F223 Introduction to Mass Communication',
    'GS F224 Print and Audio-Visual Advertising',
    'GS F231 Dynamics of Social Change',
    'GS F232 Introductory Psychology',
    'GS F233 Public Policy',
    'GS F234 Development Economics',
    'GS F241 Creative Writing',
    'GS F242 Cultural Studies',
    'GS F243 Current Affairs',
    'GS F244 Reporting and Writing for Media',
    'GS F245 Effective Public Speaking',
    'GS F266 Study Project',
    'GS F311 Introduction to Conflict Management',
    'GS F312 Applied Philosophy',
    'GS F313 Marxian Thoughts',
    'GS F321 Mass Media Content & Design',
    'GS F322 Critical Analysis of Literature and Cinema',
    'GS F325 Journalism',
    'GS F326 Creative Thinking',
    'GS F327 Selected Reading',
    'GS F331 Techniques in Social Research',
    'GS F332 Contemporary India',
    'GS F333 Public Administration',
    'GS F334 Global Business, Technology and Knowledge',
    'GS F342 Computer Mediated Communication',
    'GS F343 Short Film and Video Production',
    'GS F344 Copywriting',
    'GS F345 Constitution of India',
    'GS F366 Lab Project',
    'GS F367 Lab Project',
    'GS F491 Special Project',
    'HSS F211 Introduction to Arabic',
    'HSS F221 Readings from Drama',
    'HSS F222 Linguistics',
    'HSS F223 Appreciation of Indian Music',
    'HSS F224 English Skills for Academics',
    'HSS F226 Postmodernism',
    'HSS F227 Cross Cultural Skills',
    'HSS F228 Phonetics and Spoken English',
    'HSS F229 Introduction to Western Music',
    'HSS F232 Introduction to Development Studies',
    'HSS F233 Main Trends in Indian History',
    'HSS F234 Main Currents of Modern History',
    'HSS F235 Introductory Philosophy',
    'HSS F236 Symbolic Logic',
    'HSS F237 Contemporary Indian English Fiction',
    'HSS F238 Sports and Society',
    'HSS F242 Introduction to Phonology',
    'HSS F243 Introduction to Critical Pedagogy',
    'HSS F244 Crime and New Media',
    'HSS F245 Gender, Science and Technology',
    'HSS F246 Philosophy of Nāgārjuna',
    'HSS F247 Social Informatics',
    'HSS F248 Introduction to Disability Studies',
    'HSS F249 Politics in India',
    'HSS F250 Comics and Visual Culture',
    'HSS F251 Introduction to Discourse and Conversa-',
    'HSS F252 International Law',
    'HSS F253 Upcycling Theory',
    'HSS F254 Food Humanities',
    'HSS F266 Study Project',
    'HSS F267 Introduction to Ethics',
    'HSS F268 Introduction to Metaphysics',
    'HSS F311 Introduction to Videogame Studies',
    'HSS F312 Bureaucracy',
    'HSS F313 Introduction to Contemporary Arts',
    'HSS F314 Maritime Studies and Blue Economy',
    'HSS F315 Society, Business and Politics',
    'HSS F316 Popular Literature and Culture of South Asia',
    'HSS F317 Introduction to Globalization',
    'HSS F318 Introduction to Anthropology',
    'HSS F319 Lighting for Theatre and Films',
    'HSS F320 Introduction to Sociology of Water',
    'HSS F323 Organizational Psychology',
    'HSS F325 Cinematic Adaptation',
    'HSS F326 Humanities and Design',
    'HSS F327 Contemporary Drama',
    'HSS F328 Human Resource Development',
    'HSS F329 Musicology – An Introduction',
    'HSS F330 Appreciation of Art',
    'HSS F331 Sankara’s Thoughts',
    'HSS F332 Cinematic Art',
    'HSS F333 Comparative Religion',
    'HSS F334 Srimad Bhagavad Gita',
    'HSS F335 Literary Criticism',
    'HSS F336 Modern Fiction',
    'HSS F337 English Literary Forms and Movements',
    'HSS F338 Comparative Indian Literature',
    'HSS F339 Theatre Art-Acting and Production',
    'HSS F340 Post Colonial Literature',
    'HSS F341 Performance Design',
    'HSS F342 Advanced Communicative English',
    'HSS F343 Professional Ethics',
    'HSS F344 Heritage of India',
    'HSS F345 Gandhian Thoughts',
    'HSS F346 International Relations',
    'HSS F347 Introduction to Carnatic Music',
    'HSS F348 Introduction to Hindustani Music',
    'HSS F349 Ecocriticism',
    'HSS F350 Human Rights: History, Theory & Practice',
    'HSS F351 Social and Political Ecology',
    'HSS F352 Technology, Work and Society',
    'HSS F353 Philosophy of Aesthetics',
    'HSS F354 Introduction to Islamic Economy',
    'HSS F355 Dictatorship, Democracy & Development',
    'HSS F356 Social Movements and Protest Politics',
    'HSS F361 Urban Policy and Governance',
    'HSS F362 Local Governance and Participation',
    'HSS F363 Disaster and Development',
    'HSS F364 Political Economy of Gulf Cooperation Coun-',
    'HSS F365 Science of Sustainable Happiness',
    'HSS F368 Asian Cinemas and Cultures',
    'HSS F369 Caste and Gender in India',
    'HSS F371 Cities-Life, Issues and Conflicts',
    'HSS F372 Introduction to Social Psychology',
    'HSS F373 Shakespeare and Popular Culture',
    'HSS F374 Urban Modernity and the Renewal of Paris',
    'HSS F375 Business and Politics in Colonial and Post',
    'HSS F378 Cinemas of India: From Past to Present',
    'HSS F379 Introduction to Philosophy of Science',
    'HSS F380 Performance Studies',
    'HSS F381 Environmental Sustainability Ventures',
    'HSS F382 Housing: programs, policies and practices',
    'HSS F383 Introduction to Museum Studies',
    'HSS F384 Indian National Movement',
    'HSS F385 Mental Health Literacy for Youth',
    'HSS F386 Ocean Humanities',
    'HSS F387 History of Transport and Mobility in',
    'HSS F388 Gandhi in Literature',
    'HSS F389 Introduction to Data and Society',
    'HSS F390 Science and the Humanities: the Two',
    'HSS F391 Acoustic Humanities',
    'HSS F392 Crisis Communication',
    'HSS F393 Introduction to Metacognition',
    'HSS F394 The Study of Aging and Society',
    'HSS F395 Chinese Politics',
    'HSS F396 Indian Psychology',
    'HSS F398 Migration and Diaspora Studies',
    'HSS F399 Introduction to American Literature',
    'HSS G511 Philosophical Foundations of Liberal',
    'HSS G512 Theoretical Approaches to Liberal Studies',
    'HSS N201T Intro to Photography*',
    'HSS N202T Ind C Dance Bharatnatyam*',
    'HSS N203T Basic Arabic',
    'HSS N301T Elements of Dance',
    'HUM G511 Introduction to Health Systems',
    'INSTR F211 Electrical Machines',
    'INSTR F212 Electromagnetic Theory',
    'INSTR F214 Electronic Devices',
    'INSTR F215 Digital Design',
    'INSTR F216 Electronic Devices Simulation Laboratory',
    'INSTR F241 Microprocessors and Interfacing',
    'INSTR F242 Control Systems',
    'INSTR F243 Signals & Systems',
    'INSTR F244 Microelectronic Circuits',
    'INSTR F266 Study Project',
    'INSTR F311 Electronic Instrumentation & Instrumenta-',
    'INSTR F312 Transducers and Measurement Systems',
    'INSTR F313 Analog & Digital VLSI Design',
    'INSTR F341 Analog Electronics',
    'INSTR F342 Power Electronics',
    'INSTR F343 Industrial Instrumentation and Control',
    'INSTR F366 Lab Project',
    'INSTR F367 Lab Project',
    'INSTR F376 Design Project',
    'INSTR F377 Design Project',
    'INSTR F411 Opto-Electronic Instruments',
    'INSTR F412 Analysis Instrumentation',
    'INSTR F413 Advanced Process Control',
    'INSTR F414 Telecommunication Switching Systems &',
    'INSTR F415 Digital Control',
    'INSTR F419 Virtual Instrumentation',
    'INSTR F420 Design of Instrumentation Systems',
    'INSTR F422 Instrumentation for Petrochemical Indus-',
    'INSTR F423 Electronic Material Design and Simula-',
    'INSTR F424 Smart Grid for Sustainable Energy',
    'INSTR F428 Energy Storage Systems',
    'INSTR F432 Medical Instrumentation',
    'INSTR F438 Electric Vehicles',
    'INSTR F473 Wind Electrical Systems',
    'INSTR F491 Special Project',
    'INSTR G611 Advanced Control Systems',
    'INSTR G612 Instrumentation Systems',
    'INSTR G621 Industrial Automation',
    'IS F211 Data Structures & Algorithms',
    'IS F213 Object Oriented Programming',
    'IS F214 Logic in Computer Science',
    'IS F222 Discrete Structures for Computer Science',
    'IS F241 Digital Electronics and Microprocesors',
    'IS F242 Computer Organization',
    'IS F243 Database Systems & Application',
    'IS F266 Study Project',
    'IS F301 Principles of Programming Languages',
    'IS F303 Computer Networks',
    'IS F311 Computer Graphics',
    'IS F322 Software Testing',
    'IS F341 Software Engineering',
    'IS F342 Compiler Design',
    'IS F366 Lab Project',
    'IS F367 Lab Project',
    'IS F372 Operating Systems',
    'IS F376 Design Project',
    'IS F377 Design Project',
    'IS F462 Network Programming',
    'IS F491 Special Project',
    'ITEB G621 Supply Chain Management',
    'JAP N101T Beginning Japanese',
    'MAC F211 Linear Algebra and Its Applications',
    'MAC F212 Object Oriented Programming',
    'MAC F213 Discrete Mathematics',
    'MAC F214 Elementary Real Analysis',
    'MAC F241 Numerical Analysis',
    'MAC F242 Data Structures & Algorithms',
    'MAC F243 Numerical Optimization',
    'MAC F244 Stochastic Calculus and Application to Fi-',
    'MAC F245 Scientific Computing Laboratory',
    'MAC F266 Study Project',
    'MAC F311 Algebra I',
    'MAC F312 Foundations of Data Science',
    'MAC F313 Statistical Data Analysis',
    'MAC F314 Mathematical Modelling',
    'MAC F341 Design and Analysis of Algorithms',
    'MAC F342 Computational Partial Differential Equations',
    'MAC F366 Laboratory Project',
    'MAC F367 Laboratory Project',
    'MAC F376 Design Project',
    'MAC F377 Design Project',
    'MAC F411 Computation of Option Pricing Models',
    'MAC F491 Special Project',
    'MATH F101 Multivariable Calculus',
    'MATH F102 Linear Algebra and Complex Variables',
    'MATH F111 Mathematics I',
    'MATH F112 Mathematics II',
    'MATH F113 Probability & Statistics',
    'MATH F114 Mathematics for Business',
    'MATH F211 Mathematics III',
    'MATH F212 Optimization',
    'MATH F213 Discrete Mathematics',
    'MATH F214 Elementary Real Analysis',
    'MATH F215 Algebra I',
    'MATH F231 Number Theory',
    'MATH F241 Mathematical Methods',
    'MATH F242 Operations Research',
    'MATH F243 Graphs and Networks',
    'MATH F244 Measure and Integration',
    'MATH F266 Study Project',
    'MATH F311 Introduction to Topology',
    'MATH F312 Ordinary Differential Equations',
    'MATH F313 Numerical Analysis',
    'MATH F314 Algebra II',
    'MATH F315 Introduction to Statistical Inference',
    'MATH F316 Matrix Theory and Linear Estimation',
    'MATH F317 Sampling Theory',
    'MATH F341 Introduction to Functional Analysis',
    'MATH F342 Differential Geometry',
    'MATH F343 Partial Differential Equations',
    'MATH F344 Mathematical Fluid Dynamics',
    'MATH F353 Statistical Inference and Applications',
    'MATH F354 Complex Analysis',
    'MATH F366 Lab Project',
    'MATH F367 Lab Project',
    'MATH F376 Design Project',
    'MATH F377 Design Project',
    'MATH F378 Advanced Probability Theory',
    'MATH F420 Mathematical Modeling',
    'MATH F421 Combinatorial Mathematics',
    'MATH F422 Numerical Methodology for Partial Differ-',
    'MATH F423 Introduction to Algebraic Topology',
    'MATH F424 Applied Stochastic Process',
    'MATH F425 Numerical Linear Algebra',
    'MATH F426 Mathematical Theory of Finite Element',
    'MATH F427 Statistical Simulation and Data Analysis',
    'MATH F428 Time Series Analysis and Forecasting',
    'MATH F429 Modern Theory of Partial Differential',
    'MATH F431 Distribution Theory',
    'MATH F432 Applied Statistical Methods',
    'MATH F441 Discrete Mathematical Structures',
    'MATH F444 Numerical Solutions of Ordinary Differen-',
    'MATH F445 Mathematical Fluid Dynamics',
    'MATH F456 Cosmology',
    'MATH F471 Nonlinear Optimization',
    'MATH F481 Commutative Algebra',
    'MATH F491 Special Projects',
    'MATH F492 Wavelet analysis and applications',
    'MATH G511 Design and Analysis of Algorithms',
    'MATH G512 Selected Topics in Advanced Mathematics',
    'MATH G513 Topics in Algebra',
    'MATH G514 Topics in Analysis',
    'MATH G515 Topics in Differential Equations',
    'MATH G516 Topics in Topology',
    'MATH G521 Applied Functional Analysis',
    'MATH G531 Number Theory',
    'MATH G541 Advanced Methods in Discrete',
    'MATH G611 Algebraic Number Theory',
    'MATH G612 Riemann Surfaces',
    'MATH G621 Fibre Bundles',
    'MATH G622 Algebraic Geometry',
    'MATH G632 Lie Groups and Lie Algebras',
    'MATH G642 Complex Manifolds',
    'MBA G501 Managerial Economics',
    'MBA G502 Business Structure & Processes',
    'MBA G503 Managerial Skills',
    'MBA G504 Legal and Economic Environment of',
    'MBA G505 Management Framework & Functions',
    'MBA G506 Negotiation Skills and Techniques',
    'MBA G507 International Financial Markets & Services',
    'MBA G508 Functions and Working of Stock',
    'MBA G509 Investment Banking and Financial Services',
    'MBA G510 Human Resource Management',
    'MBA G511 Organisational Behaviour',
    'MBA G512 Manufacturing Strategy',
    'MBA G513 Quantitative Methods',
    'MBA G514 Technology Management',
    'MBA G515 Financial and Management Accounting',
    'MBA G516 Corporate Finance and Taxation',
    'MBA G517 Business and Society',
    'MBA G518 Marketing',
    'MBA G519 Production and Operations Management',
    'MBA G520 Business Policy and Strategic',
    'MBA G521 Supply Chain Management',
    'MBA G522 Total Quality Management',
    'MBA G523 Project Management',
    'MBA G524 International Business',
    'MBA G525 R&D Management',
    'MBA G526 Database Management Systems',
    'MBA G527 e-Business and Internet Marketing',
    'MBA G528 Internet Security and Cyber Laws',
    'MBA G529 Recent Advances in ETM',
    'MBA G530 Project Appraisal',
    'MBA G531 Managerial Communication',
    'MBA G532 Risk Management and Insurance',
    'MBA G533 Advertising and Sales Promotion',
    'MBA G534 Introduction to Business Sustainabiligy',
    'MBA G535 Cross Cultural Management',
    'MBA G536 Strategic Financial Management',
    'MBA G537 Security Analysis and Portfolio',
    'MBA G538 Marketing Models',
    'MBA G539 Six Sigma',
    'MBA G540 Sports Marketing',
    'MBA G541 Operations Strategy',
    'MBA G542 Consumer Behaviour',
    'MBA G543 Leading Modern Organizations',
    'MBA G544 Organizational Theory & Behaviour',
    'MBA G545 Management Science',
    'MBA G546 Business Statistics',
    'MBA G547 Accounting for Managers',
    'MBA G548 Strategic Marketing',
    'MBA G549 Introduction to Systems & Sustainability',
    'MBA G550 Critical and Design Thinking',
    'MBA G551 Internetworking Technologies',
    'MBA G552 Total Productive Maintenance',
    'MBA G553 Organizational Change and Development',
    'MBA G554 Innovative Leadership',
    'MBA G555 International Human Resource Management',
    'MBA G556 Performance Management',
    'MBA G557 Economic Environment of Business',
    'MBA G558 Operations and Supply Chain Management',
    'MBA G559 Corporate Finance',
    'MBA G560 Marketing Research & Metrics',
    'MBA G561 Business Analytics',
    'MBA G562 Services Marketing',
    'MBA G563 Industrial Marketing',
    'MBA G564 Decision Making',
    'MBA G565 Information & Knowledge Management Sys-',
    'MBA G566 Strategic Management',
    'MBA G567 Technology Innovation & Entrepreneurship',
    'MBA G568 International Business Strategy & Opera-',
    'MBA G571 Management Information Systems',
    'MBA G574 Retail Management Systems',
    'MBA G575 Financial Engineering',
    'MBA G576 Digital Marketing',
    'MBA G577 Supply Chain Analytics',
    'MBA G578 Game Theory and Business Strategy',
    'MBA G579 Management Practice',
    'MBA G581 Expert Systems',
    'MBA G582 Creating & Leading Entrepreneurial Organ-',
    'MBA G583 Marketing Research',
    'MBA G586 Product and Brand Management',
    'MBA G588 Services Management System',
    'MBA G589 Enterprise Resource Planning',
    'MBA G593 Business Analysis and Valuation',
    'MBA G622 Software Project Management',
    'ME F110 Workshop Practice',
    'ME F112 Workshop Practice',
    'ME F211 Mechanics of Solids',
    'ME F212 Fluid Mechanics',
    'ME F213 Materials Science & Engineering',
    'ME F214 Applied Thermodynamics',
    'ME F215 Mechanical Engineering Laboratory',
    'ME F216 Materials Science and Engineering',
    'ME F217 Applied Thermodynamics',
    'ME F218 Advanced Mechanics of Solids',
    'ME F219 Manufacturing Processes',
    'ME F220 Heat Transfer',
    'ME F221 Mechanisms and Machines',
    'ME F241 Machine Design & Drawing',
    'ME F242 IC Engines',
    'ME F243 Production Techniques I',
    'ME F244 Kinematics & Dynamics of Machinery',
    'ME F266 Study Project',
    'ME F311 Heat Transfer',
    'ME F312 Advanced Mechanics of Solids',
    'ME F313 Production Techniques II',
    'ME F314 Design of Machine Elements',
    'ME F315 Advanced Manufacturing Processes',
    'ME F316 Manufacturing Management',
    'ME F317 Engines, Motors, and Mobility',
    'ME F318 Computer-Aided Design',
    'ME F319 Vibrations and Control',
    'ME F320 Engineering Optimization',
    'ME F321 Data Mining in Mechanical Sciences',
    'ME F323 Energy Storage Technologies',
    'ME F324 Cell and Tissue Biomechanics',
    'ME F325 Fundamentals of Soft Matter',
    'ME F326 Mechanics of Sports',
    'ME F340 Introduction to Sports Engineering',
    'ME F341 Prime Movers & Fluid Machines',
    'ME F342 Computer Aided Design',
    'ME F343 Mechanical Vibrations',
    'ME F344 Engineering Optimization',
    'ME F366 Lab Project',
    'ME F367 Lab Project',
    'ME F376 Design Project',
    'ME F377 Design Project',
    'ME F411 Fluid Power Systems',
    'ME F412 Production Planning and Control',
    'ME F413 Nonlinear Vibrations',
    'ME F414 Fuel Cell Science and Technology',
    'ME F415 Gas Dynamics',
    'ME F416 Reverse Engineering and Rapid Prototyping',
    'ME F417 Advanced Metal Forming',
    'ME F418 Rocket and Spacecraft Propulsion',
    'ME F419 Total Product Integration Engineering',
    'ME F420 Power Plant Engineering',
    'ME F423 Micro Fluidics and its Application',
    'ME F424 Energy Management',
    'ME F425 Additive Manufacturing',
    'ME F426 Industry',
    'ME F427 Continuum Mechanics',
    'ME F428 Smart Materials',
    'ME F429 Micro-Nanoscale Heat Transport',
    'ME F430 Fluid-Structure Interactions',
    'ME F432 Computer Aided Manufacturing',
    'ME F433 Solar Thermal Process Engineering',
    'ME F434 Digital Twins in Mechanical Engineering',
    'ME F435 Shape Memory Alloys: Fundamentals and',
    'ME F436 Sustainable Energy Informatics',
    'ME F437 Thermo-fluidic of Food Process Engineering',
    'ME F438 Micro and Nano Energy Harvesting',
    'ME F439 Unmanned Aerial Vehicle',
    'ME F441 Automotive Vehicles',
    'ME F443 Quality Control, Assurance and Reliability',
    'ME F451 Mechanical Equipment Design',
    'ME F452 Composite Materials & Design',
    'ME F461 Refrigeration and Air conditioning',
    'ME F472 Precision Engineering',
    'ME F481 Project Appraisal',
    'ME F482 Combustion',
    'ME F483 Wind Energy',
    'ME F484 Automotive Technology',
    'ME F485 Numerical Techniques for Fluid Flow and Heat',
    'ME F491 Special Project',
    'ME G511 Mechanisms & Robotics',
    'ME G512 Finite Element Methods',
    'ME G513 Heating and Cooling of Buildings',
    'ME G514 Turbomachinery',
    'ME G515 Computational Fluid Dynamics',
    'ME G516 Energy Systems Engineering',
    'ME G517 Applied Mathematics',
    'ME G518 Advanced Thermodynamics for Sustainable',
    'ME G519 Advanced Fluid Dynamics',
    'ME G521 Mechanical System Design',
    'ME G532 Machine Tool Engineering',
    'ME G533 Conduction and Radiation Heat Transfer',
    'ME G534 Convective Heat and Mass Transfer',
    'ME G535 Advanced Engineering Mathematics',
    'ME G536 Thermal Equipment Design',
    'ME G537 Cryogenic Engineering',
    'ME G538 Toyota Production System',
    'ME G539 Computer Integrated Manufacturing',
    'ME G542 Advanced welding techniques',
    'ME G543 Natural Refrigerants and Application',
    'ME G544 Multibody Dynamics',
    'ME G545 Deep Neural Networks',
    'ME G546 Advanced Driver Assistance System',
    'ME G547 Connected Manufacturing',
    'ME G611 Computer Aided Analysis and Design',
    'ME G612 Plastics Engineering',
    'ME G613 Advanced Finite Element Modelling &',
    'ME G614 Topology Optimization of Machine',
    'ME G621 Fluid Dynamics',
    'ME G622 Multiphase Flow',
    'ME G623 Advanced Gas Dynamics',
    'ME G624 Microfluidics for Thermal Engineers',
    'ME G625 Thermo-fluidics of Food Processing',
    'ME G626 Batteries, Fuel Cells and Other',
    'ME G627 Artificial Intelligence in Energy Systems',
    'ME G628 Electric Vehicles',
    'ME G629 Thermal Management in Packaging',
    'ME G630 Cryogenic Engineering and Applications',
    'ME G631 Advanced Heat Transfer',
    'ME G632 Energy Auditing and Management',
    'ME G633 Wind Energy Systems Modelling and Analysis',
    'ME G634 Modelling and Simulation of Bioenergy',
    'ME G635 Finite Element Modelling of Fluid Flows',
    'ME G636 Thermal and Hybrid Power Generation',
    'ME G637 Turbulent Flows',
    'ME G638 Geophysical Fluid Dynamics',
    'ME G639 Environmental Fluid Mechanics',
    'ME G640 Rocket and Space Craft Propulsion',
    'ME G641 Theory of Elasticity and Plasticity',
    'ME G642 Experimental Techniques in Thermal',
    'MEL G512 Optoelectronic Devices, Circuits and Sys-',
    'MEL G514 Nanoelectronic Memories and Technology',
    'MEL G521 Novel Memory Concepts and Technology',
    'MEL G522 Digitally Assisted Analog Circuits',
    'MEL G523 Phase and Frequency Synthesis of Analog',
    'MEL G528 Digital VLSI Design',
    'MEL G532 Hardware Security',
    'MEL G533 SOC Test and Power Aware Testing',
    'MEL G541 Hardware and Software Formal Verification',
    'MEL G611 IC Fabrication Technology',
    'MEL G612 Integrated Electronics Systems Design',
    'MEL G621 VLSI Design',
    'MEL G622 Introduction to Artificial Neural Networks',
    'MEL G623 Advanced VLSI Design',
    'MEL G624 Advanced VLSI Architectures',
    'MEL G625 Advanced Analog and Mixed Signal Design',
    'MEL G626 VLSI Test and Testability',
    'MEL G627 VLSI Fabrication Technology',
    'MEL G631 Physics and Modelling of Microelectronic',
    'MEL G632 Analog IC Design',
    'MEL G633 Data Converters',
    'MEL G634 In-Memory Computing',
    'MEL G635 High Speed SerDes Design',
    'MEL G636 Network Embedded Applications',
    'MEL G641 CAD for IC Design',
    'MEL G642 VLSI Architectures',
    'MEL G643 Verification, Test and Testability of VLSI',
    'MF F211 Mechanics of Solids',
    'MF F212 Fluid Mechanics',
    'MF F213 Materials Science & Engineering',
    'MF F214 Applied Thermodynamics',
    'MF F215 Mechanical Engineering Laboratory',
    'MF F216 Materials Science and Engineering',
    'MF F217 Machine Drawing',
    'MF F218 Transport Phenomena in Manufacturing',
    'MF F219 Operations Management',
    'MF F220 Metrology and Quality Assurance',
    'MF F221 Mechanisms and Machines',
    'MF F222 Casting, Forming and Welding',
    'MF F241 Machine Design & Drawing',
    'MF F242 Manufacturing Management',
    'MF F243 Manufacturing Processes',
    'MF F244 Kinematics & Dynamics of Machinery',
    'MF F266 Study Project',
    'MF F311 Mechatronics & Automation',
    'MF F312 Tool and Fixture Design',
    'MF F313 Metal Forming and Machining',
    'MF F314 Design of Machine Elements',
    'MF F315 Automation and Control',
    'MF F316 Machining and Machine Tools',
    'MF F317 Computer Aided Design and Manufacturing',
    'MF F318 Nontraditional Manufacturing Processes',
    'MF F319 Supply Chain Management',
    'MF F320 Engineering Optimization',
    'MF F321 Procurement Management',
    'MF F341 Design of Machine Tools',
    'MF F342 Computer Aided Design',
    'MF F343 Casting and Welding',
    'MF F344 Engineering Optimization',
    'MF F366 Lab Project',
    'MF F367 Lab Project',
    'MF F376 Design Project',
    'MF F377 Design Project',
    'MF F411 Fluid Power Systems',
    'MF F412 Automotive Systems',
    'MF F413 Mechanical Vibrations and Acoustics',
    'MF F414 Manufacturing Excellence',
    'MF F415 Noise Engineering',
    'MF F416 Work System Design',
    'MF F418 Lean Manufacturing',
    'MF F421 Supply Chain Management',
    'MF F422 Supply Chain Modelling and Empirical Analy-',
    'MF F442 Advances in Materials Science',
    'MF F453 Industrial Relations',
    'MF F463 Maintenance and Safety',
    'MF F471 Instrumentation and Control',
    'MF F472 Precision Engineering',
    'MF F473 Product Design and Development',
    'MF F474 Product Design and Development Projects',
    'MF F485 Sustainable Manufacturing',
    'MF F491 Special Project',
    'MGTS F211 Principles of Management',
    'MGTS F311 Marketing',
    'MGTS F313 Product and Brand Management',
    'MGTS F314 Essentials of Financial Management',
    'MGTS F315 Foundations of Business Analytics',
    'MGTS F316 Managerial and Leadership Skills',
    'MGTS F351 Organisational Behaviour n',
    'MGTS F433 Advertising and Sales Promotion',
    'MGTS G511 Advanced Marketing Theories and Adver-',
    'MGTS G513 Public Programme Evaluation',
    'MGTS G521 Business Policy -Structure and Organisa-',
    'MGTS G531 Recent Advances in Organisation Behav-',
    'MGTS G541 Management Information and Decision',
    'MGTS G551 Frontiers in Financial Management',
    'MGTS G561 Institutional Finance and Project Appraisal',
    'MPBA G501 Managerial Economics',
    'MPBA G502 Financial Statement Analysis & Reporting',
    'MPBA G503 Marketing Management',
    'MPBA G504 Managing People & Organization',
    'MPBA G505 Statistics & Basic Econometrics',
    'MPBA G506 Data Management and Warehousing',
    'MPBA G507 Programming for Analytics',
    'MPBA G508 Strategic Management',
    'MPBA G509 Corporate Finance',
    'MPBA G510 Operations & Supply Chain Management',
    'MPBA G511 Data Visualization, Ethics and Data',
    'MPBA G512 Time Series Analysis and Forecasting',
    'MPBA G513 Predictive Analytics',
    'MPBA G514 Deep Learning for Business',
    'MPBA G515 Prescriptive Analytics with Mathe-',
    'MPBA G516 Advanced Spreadsheet & Macro Pro-',
    'MPBA G517 Big Data Analytics',
    'MPBA G518 Bayesian Analysis',
    'MPBA G519 Natural Language Processing for Busi-',
    'MPBA G520 Analytics for Supply Chain',
    'MPBA G521 Supply Chain Finance',
    'MPBA G522 Discrete Event Simulation',
    'MPBA G523 IT Project Management',
    'MPBA G524 Marketing Analytics',
    'MPBA G525 Digital Analytics',
    'MPBA G526 Pricing Analytics',
    'MPBA G527 Retail Analytics',
    'MPBA G528 Customer Engagement and Analytics',
    'MPBA G529 Marketing Research & Metrics',
    'MPBA G530 Financial Analytics',
    'MPBA G531 Financial Derivatives and Analysis',
    'MPBA G532 Financial Modelling and Valuation',
    'MPBA G533 Financial Technology',
    'MPBA G534 People Analytics',
    'MPBA G535 Strategy Analytics',
    'MPBA G536 Knowledge Management and Digital',
    'MPBA G537 Data Structures and Algorithmic Thinking',
    'MPBA G538 Critical Product Management',
    'MPH G510 Biostatistics & Computers in Public Health',
    'MPH G512 Environmental & Occupational Health',
    'MPH G513 Public Health & Diseases',
    'MPH G515 Communication in Health Care',
    'MPH G521 Health Care Management',
    'MPH G522 Preventive Nutrition & Health Promotion',
    'MPH G523 Epidemic & Disaster Management',
    'MPH G531 Health Economics & Financial Management',
    'MPH G535 Family & Community Health Measures',
    'MPH G537 Law & Ethics in Public Health',
    'MPH G538 Telemedicine',
    'MPH G539 Inter -sectoral co-ordination in Health Ser-',
    'MPH G540 Role of Voluntary bodies/ NGO’s in Public',
    'MPH G613 Health Systems and Society',
    'MPH G661 Research Methodology I',
    'MPH G665 Hospital Operations Management',
    'MPH G681 Strategic Management',
    'MPH G692 Epidemiology',
    'MSE G511 Mechatronics',
    'MSE G512 Manufacturing Planning and Control',
    'MSE G513 Maintenance Engineering',
    'MSE G514 Leadership and Managing Change',
    'MSE G515 Supply Chain Modelling and Empirical',
    'MSE G521 World-Class Manufacturing',
    'MSE G531 Concurrent Engineering',
    'MSE G601 Supply Chain Management',
    'MST F331 Materials Characterization',
    'MST F332 Materials Processing',
    'MST F333 Introduction to Biomaterials',
    'MST F334 Materials for Catalytic applications',
    'MST F335 Coating and Thin film technology',
    'MST F336 Glass Technology',
    'MST F337 Materials for Energy Applications',
    'MST F338 Metals and Alloys',
    'MST F339 Polymer Materials',
    'MST G511 Nondestructive Testing Techniques',
    'MST G512 Ceramics Technology',
    'MST G521 Materials Characterization Techniques',
    'MST G522 Advanced Composites',
    'MST G531 Experimental Stress Analysis Techniques',
    'MST G532 Electronic Materials',
    'MUSIC N103T Indian Classical Music (Vocal) I',
    'MUSIC N104T Indian Classical Music (Vocal) II',
    'MUSIC N105T Western Classical Music I',
    'MUSIC N106T Western Classical Music II',
    'MUSIC N111T Hindi Classical Music (Instrumental) I',
    'MUSIC N112T Hindi Classical Music (Instrumental) II',
    'MUSIC N113T Indian Classical Music (Instrumental) I',
    'MUSIC N114T Indian Classical Music (Instrumental) II',
    'MUSIC N203T Indian Classical Music (Vocal) III',
    'MUSIC N204T Indian Classical Music (Vocal) IV',
    'MUSIC N205T Western Classical Music III',
    'MUSIC N206T Western Classical Music IV',
    'MUSIC N213T Indian Classical Music (Instrumental) III',
    'MUSIC N214T Indian Classical Music (Instrumental) IV',
    'MUSIC N303T Advanced Indian Music Practice (Vocal)',
    'MUSIC N313T Advanced Indian Music Practice (Instru-',
    'PHA F211 Pharmaceutical Analysis',
    'PHA F212 Dispensing Pharmacy',
    'PHA F213 Microbiology',
    'PHA F214 Anatomy Physiology & Hygiene',
    'PHA F215 Introduction to Molecular Biology &',
    'PHA F216 Pharmaceutical Formulations I',
    'PHA F217 Pharmaceutical Microbiology',
    'PHA F241 Pharmaceutical Chemistry',
    'PHA F242 Biological Chemistry',
    'PHA F243 Industrial Pharmacy',
    'PHA F244 Physical Pharmacy',
    'PHA F266 Study Project',
    'PHA F311 : Pharmacology I',
    'PHA F311 Pharmacology I',
    'PHA F312 Medicinal Chemistry I',
    'PHA F313 Instrumental Methods of Analysis',
    'PHA F314 Pharmaceutical Formulations and Biophar-',
    'PHA F315 Pharmaceutical Formulations II',
    'PHA F316 Pharmaceutical Regulatory Science',
    'PHA F317 Safety Pharmacology and Toxicology',
    'PHA F341 Pharmacology II',
    'PHA F342 Medicinal Chemistry II',
    'PHA F343 Forensic Pharmacy',
    'PHA F344 : Natural Drugs',
    'PHA F344 Natural Drugs',
    'PHA F366 Lab Project',
    'PHA F367 Lab Project',
    'PHA F376 Design Project',
    'PHA F377 Design Project',
    'PHA F413 Pharmaceutical Management and Quality',
    'PHA F414 Biopharmaceutics',
    'PHA F415 Pathophysiology',
    'PHA F416 Chemistry of Synthetic Drugs',
    'PHA F417 Pharmacoeconomics',
    'PHA F418 Biopharmaceutics and Pharmacokinetics',
    'PHA F419 Herbal Drug Technology',
    'PHA F422 Cosmetic Science',
    'PHA F432 Hospital Pharmacy',
    'PHA F441 Biochemical Engineering',
    'PHA F442 Applied Pharmaceutical Chemistry',
    'PHA F461 Phytochemistry',
    'PHA F491 Special Projects',
    'PHA G510 Application of Statistics and Computer in',
    'PHA G511 Fermentation & Biotechnology',
    'PHA G512 Chemistry of Natural Drugs',
    'PHA G521 Molecular Biology & Immunology',
    'PHA G522 Chemistry of Macromolecules',
    'PHA G523 Total Quality Management and Regulatory',
    'PHA G528 Developmental Neuroscience',
    'PHA G529 Neuropharmacology',
    'PHA G531 Disinfection and Sterilization',
    'PHA G532 Quality Assurance & Regulatory Affairs',
    'PHA G533 Pharmaceutical Process Chemistry',
    'PHA G534 Separation and Structure Elucidation Tech-',
    'PHA G535 Biomaterials',
    'PHA G536 Cosmetics and Cosmeceuticals',
    'PHA G537 Parenteral Product Development',
    'PHA G538 Immunopharmacology',
    'PHA G539 Principles of Drug Discovery',
    'PHA G540 Modern Pharmaceutical Analytical Tech-',
    'PHA G541 Computer Aided Drug Design',
    'PHA G542 Advanced Physical Pharmaceutics',
    'PHA G543 Clinical Research',
    'PHA G544 Advanced Pharmaceutical Chemistry',
    'PHA G545 Intellectual property rights and Pharmaceu-',
    'PHA G546 Pharmaceutical Biostatistics',
    'PHA G547 Quality -by-Design in Pharmaceutical',
    'PHA G548 Chemistry of Natural Drugs',
    'PHA G611 Advanced Pharmacology',
    'PHA G612 Pharmacokinetics & Clinical Pharmacy',
    'PHA G613 Pharmaceutical Biotechnology',
    'PHA G614 Clinical Pharmacy and Therapeutics',
    'PHA G615 Pharmacy Practice',
    'PHA G616 Pharmaceutical Administration and Manage-',
    'PHA G617 Advanced Drug Delivery Systems',
    'PHA G618 Reterosynthetic Analysis',
    'PHA G619 Screening Methods and Techniques In Phar-',
    'PHA G621 Advanced Medicinal Chemistry',
    'PHA G622 Chemistry of Natural Drugs & Macromole-',
    'PHA G623 Pharmaceutical Applications of',
    'PHA G624 Principles of Toxicology',
    'PHA G625 Cellular and Molecular Pharmacology',
    'PHA G626 Pharmacovigilance',
    'PHA G627 Medical Devices and Testing',
    'PHA G632 Dosage Form Design',
    'PHA G642 Laboratory Project',
    'PHA G645 Molecular Pharmacology',
    'PHY F101 Oscillations and Waves',
    'PHY F102 Introduction to Oscillations and Waves',
    'PHY F110 Physics Laboratory',
    'PHY F111 Mechanics, Oscillations and Waves',
    'PHY F112 General Physics',
    'PHY F211 Classical Mechanics',
    'PHY F212 Electromagnetic Theory I',
    'PHY F213 Optics',
    'PHY F214 Electricity, Magnetism, and Optics Lab',
    'PHY F215 Introduction to Astronomy and Astrophysics',
    'PHY F221 Modern Physics',
    'PHY F241 Electromagnetic Theory II',
    'PHY F242 Quantum Mechanics I',
    'PHY F243 Mathematical Methods of Physics',
    'PHY F244 Modern Physics Lab',
    'PHY F266 Study Project',
    'PHY F311 Quantum Mechanics II',
    'PHY F312 Statistical Mechanics',
    'PHY F313 Computational Physics',
    'PHY F315 Theory of Relativity',
    'PHY F316 Musical Acoustics',
    'PHY F317 Introduction to Radio Astronomy',
    'PHY F318 Atoms and Photons',
    'PHY F319 Spacecraft Systems',
    'PHY F320 Space Physics',
    'PHY F341 Solid State Physics',
    'PHY F342 Atomic and Molecular Physics',
    'PHY F343 Nuclear and Particle Physics',
    'PHY F344 Advanced Physics Lab',
    'PHY F345 Quantum Mechanics for Engineers',
    'PHY F346 Laser Science and Technology',
    'PHY F366 Lab Project',
    'PHY F367 Lab Project',
    'PHY F376 Design Project',
    'PHY F377 Design Project',
    'PHY F378 Plasma Physics and its Applications',
    'PHY F379 Thin Film Technology',
    'PHY F412 Introduction to Quantum Field Theory',
    'PHY F413 Particle Physics',
    'PHY F414 Physics of Advanced Materials',
    'PHY F415 General Theory of Relativity and Cosmology',
    'PHY F416 Soft Condensed Matter Physics',
    'PHY F417 Experimental Methods of Physics',
    'PHY F418 Lasers and Applications',
    'PHY F419 Advanced Solid State Physics',
    'PHY F420 Quantum Optics',
    'PHY F421 Advanced Quantum Mechanics',
    'PHY F422 Group Theory and Applications',
    'PHY F423 Special Topics in Statistical Mechanics',
    'PHY F424 Advanced Electrodynamics',
    'PHY F426 Physics of Semiconductor Devices',
    'PHY F427 Atmospheric Physics',
    'PHY F428 Quantum Information Theory',
    'PHY F431 Geometrical Methods in Physics',
    'PHY F432 Classical Theory of Fields: A Symmetry Per-',
    'PHY F433 Topics in Nonlinear Optics',
    'PHY F434 Foundations of Quantum Mechanics',
    'PHY F435 Advanced Computational Physics',
    'PHY F436 Space Science Instrumentation',
    'PHY F437 Scientific Computing and Data Analysis',
    'PHY F438 Fundamentals of Quantum Field Theory',
    'PHY F491 Special Project',
    'PHY G511 Theoretical Physics',
    'PHY G512 Advanced Quantum Field Theory',
    'PHY G513 Classical Electrodynamics',
    'PHY G514 Quantum Theory and Applications',
    'PHY G515 Condensed Matter Physics',
    'PHY G516 Statistical Physics & Applications',
    'PHY G517 Topics in Mathematical Physics',
    'PHY G518 Computational Methods in Physics',
    'PHY G521 Nuclear and Particle Physics',
    'PHY G531 Selected Topics in Solid State Physics',
    'PHY G541 Physics of Semiconductor Devices',
    'QT G511 Mathematical Foundations of Quantum',
    'QT G512 Quantum Computation and Information',
    'QT G513 Overview of Hardware for Quantum technologies',
    'QT G514 Quantum Communication and Networking',
    'QT G515 Experimental Techniques for Quantum',
    'QT G516 Quantum Algorithms and Applications',
    'QT G517 Introduction to Quantum Materials',
    'QT G518 Quantum Cryptography and Security',
    'QT G519 Atomic and Optical Technology',
    'QT G520 Quantum computing applications using',
    'QT G531 Open Quantum Systems',
    'QT G532 Quantum Algorithms',
    'QT G611 Tensor Network Methods for simulating',
    'QT G620 Quantum Metrology, Sensing and Imaging',
    'QT G621 Advanced Quantum Information Theory',
    'QT G622 Quantum Control and Interfacing Engineering',
    'QT G623 Quantum Simulations and Simulators',
    'QT G624 Post Quantum Cryptography',
    'QT G625 Quantum Advanced Programming,',
    'QT G626 Quantum Software and Application',
    'QT G630 Field Theoretical Understanding of',
    'QT G631 Quantum Error Correction',
    'RIA F211 Introduction to Mechanisms and Robotics',
    'RIA F211 Materials and Mechanics for Robotics',
    'RIA F213 Foundations of Data Structures and',
    'RIA F214 Sensors, Actuators and Signal',
    'RIA F241 Artificial Intelligence for Robotics',
    'RIA F242 Control Systems',
    'RIA F243 Signals and Systems',
    'RIA F244 Embedded Systems for Robotics',
    'RIA F311 Fluid Power Systems',
    'RIA F312 Robot Dynamics & Control',
    'RIA F313 Computer Vision',
    'RIA F321 Underwater Robotics',
    'RIA F322 Autotronics and Vehicle Intelligence',
    'RIA F323 AR/VR in Robotics',
    'RIA F341 IoT for Industrial Automation',
    'RIA F342 Computer-Aided Design',
    'RIA F343 Autonomous Mobile Robotics',
    'RIA F344 Industrial Automation & Control',
    'RIA F371 Capstone Project-1',
    'RIA F372 Capstone Project-2',
    'RUS N101T Beginning Russian',
    'RUS N102T Technical Russian',
    'SAN G511 Sanitation Technology',
    'SAN G512 Sanitation and Public Health',
    'SAN G513 Sanitation Governance, Behaviour',
    'SAN G514 Sanitation Financing and Project Manage-',
    'SAN G515 Emergency Sanitation and Leadership',
    'SANS F111 Sanskrit',
    'SKILL G611 Computer Operation and Software Deve l-',
    'SKILL G612 Computer Operation and Software Devel-',
    'SKILL G621 Computer Maintenance I',
    'SKILL G622 Computer Maintenance II',
    'SKILL G631 Professional Communication I',
    'SKILL G632 Professional Communication II',
    'SKILL G641 Modern Experimental Methods I',
    'SKILL G642 Modern Experimental Methods II',
    'SKILL G651 Techniques in DevelopmentManagement I',
    'SKILL G652 Techniques in Development Management II',
    'SKILL G661 Research Methodology I',
    'SKILL G662 Research Methodology II',
    'SNS F211 Fundamentals of Nanoscience and',
    'SNS F212 Quantum Mechanics',
    'SNS F213 Material Science and Engineering',
    'SNS F214 Fundamentals of Solid State Physics',
    'SNS F241 Chemistry at Nanoscale',
    'SNS F242 Electronic Devices',
    'SNS F243 Materials & Nanoscale Characterization',
    'SNS F244 Nanomaterials Synthesis &',
    'SNS F266 Study Project',
    'SNS F311 Semiconductor Thin Film Technology',
    'SNS F312 Molecular Simulations',
    'SNS F313 Instrumental Methods of Analysis',
    'SNS F315 Nanotechnology & Nanomaterials',
    'SNS F341 Principles of Nanobiotechnology',
    'SNS F342 Principles of Nanophotonics and Devices',
    'SNS F343 Advanced Nanofabrication',
    'SNS F345 Physics and Modelling of',
    'SNS F366 Laboratory Project',
    'SNS F367 Laboratory Project',
    'SNS F376 Design Project',
    'SNS F377 Design Project',
    'SNS F491 Special Project',
    'SS G511 Design and Analysis of Algorithms',
    'SS G512 Object Oriented Programming',
    'SS G513 Network Security',
    'SS G514 Object Oriented Analysis and Design',
    'SS G515 Data Warehousing',
    'SS G516 Computer Organization & Software Systems',
    'SS G517 Data Structures & Algorithm Analysis',
    'SS G518 Database Design & Applications',
    'SS G519 Social Media Analytics',
    'SS G520 Advanced Data Mining',
    'SS G521 Fourth Generation Languages and Applica-',
    'SS G522 Software Development Standards',
    'SS G523 Software for Embedded Systems',
    'SS G527 Cloud Computing',
    'SS G531 Pervasive Computing',
    'SS G532 Information Theory',
    'SS G541 User Interfaces',
    'SS G542 Knowledge Management',
    'SS G551 Advanced Compilation Techniques',
    'SS G552 Software Testing Methodologies',
    'SS G554 Distributed Data Systems',
    'SS G562 Software Engineering & Management',
    'SS G624 Computer Based Simulation and Modlling',
    'SS G641 Management Information and Decision Sup-',
    'SS G651 Project Formulation and Preparation',
    'SS G653 Software Architectures',
]
