import { GetStaticProps } from 'next';
import Head from 'next/head'
import { useState } from 'react'
import YearComponent from './../Components/YearComponent';

export const getStaticProps: GetStaticProps = async () => {
  const fs = require('fs');
  const handoutsMap: any = {};

  const semsWithYears = fs.readdirSync('./public/handouts/');

  semsWithYears.forEach((sem: any) => {
    const semWiseHandouts = fs.readdirSync('./public/handouts/' + sem);
    handoutsMap[sem] = semWiseHandouts;
  })

  return {
    props: {
      handoutsMap
    }
  }
}

export default function Home({ handoutsMap }: any) {
  const [search, setSearch] = useState("");

  return (
    <>
      <Head>
        <title>Handouts for You.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Search box */}
      <div className='grid h-[50vh] place-items-center'>
        <div className='w-[50vw] place-items-center flex flex-col justify-between'>
          <h1 className='text-5xl p-3'>Handouts For You.</h1>
          <input type="text" placeholder="Search..." className="input input-bordered w-full max-w-xs" onChange={e => setSearch(e.target.value)} />
        </div>
      </div>

      <div className='px-20'>
        {
          Object.keys(handoutsMap).map((handoutMap: any) => {
            return <YearComponent handouts={handoutsMap[handoutMap]} year={handoutMap} key={handoutMap} searchWord={search}/>
          })
        }
      </div>
    </>
  )
}
