"""
@author: Saphereye
@about: The script using soundex algorithm to cluster similar texts together, the output is a txt file with each line containing the similar PS stations
"""

from collections import defaultdict
import jellyfish
import json

# Defining the constants
JSON_FILE = 'ps2_data.json'
OUTPUT_FILE = 'soundex_filter.txt'

# Getting the PS station names, putting in set for avoiding repetition
with open(JSON_FILE, 'r') as f:
    data = {item["name"].strip() for item in json.load(f)}

# Grouping them based on key generated by soundex algorithm
grs = defaultdict(list)
for name in data:
    grs[jellyfish.soundex(name)].append(name)

# Writing the output to output file
with open(OUTPUT_FILE, 'w') as f:
    for i, j in grs.items():
        if len(j) > 1:
            f.write(','.join(j) + '\n')