create table "public"."course_reviews" (
    "created_at" timestamp with time zone not null default now(),
    "created_by" character varying not null,
    "course" character varying not null,
    "prof" character varying not null,
    "review" text not null
);


alter table "public"."course_reviews" enable row level security;

create table "public"."ps1_responses" (
    "created_at" timestamp with time zone not null default now(),
    "email" character varying not null,
    "allotment_round" character varying,
    "year_and_sem" character varying,
    "station" character varying,
    "cgpa" numeric,
    "preference" integer,
    "id" smallint generated by default as identity not null
);


alter table "public"."ps1_responses" enable row level security;

create table "public"."ps1_reviews" (
    "created_at" timestamp with time zone not null default now(),
    "created_by" character varying not null,
    "batch" character varying not null,
    "station" character varying not null,
    "review" text not null
);


alter table "public"."ps1_reviews" enable row level security;

create table "public"."ps2_responses" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "email" character varying,
    "id_number" character varying,
    "allotment_round" character varying,
    "year_and_sem" character varying,
    "station" character varying,
    "cgpa" numeric,
    "preference" integer,
    "offshoot" integer,
    "offshoot_total" integer,
    "offshoot_type" character varying
);


alter table "public"."ps2_responses" enable row level security;

create table "public"."ps2_reviews" (
    "created_at" timestamp with time zone not null default now(),
    "created_by" character varying not null,
    "batch" character varying not null,
    "station" character varying not null,
    "review" text not null
);


alter table "public"."ps2_reviews" enable row level security;

create table "public"."rants" (
    "id" bigint generated by default as identity not null,
    "rant" text,
    "created_by" character varying,
    "created_at" bigint not null
);


alter table "public"."rants" enable row level security;

create table "public"."resources" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "link" text,
    "created_by" text,
    "created_at" timestamp with time zone not null default now(),
    "email" text,
    "score" bigint default '0'::bigint,
    "category" character varying
);


alter table "public"."resources" enable row level security;

create table "public"."si_chronicles" (
    "name" character varying not null,
    "company" text not null,
    "year" text not null,
    "cgpa" character varying,
    "role" character varying,
    "text" text
);


alter table "public"."si_chronicles" enable row level security;

create table "public"."si_companies" (
    "name" character varying not null,
    "year" character varying not null,
    "eligibility" text,
    "cgpa_cutoff" text,
    "roles" text not null,
    "selects" text,
    "selection_rounds" text,
    "stipend" text,
    "otherdetails" text
);


alter table "public"."si_companies" enable row level security;

CREATE UNIQUE INDEX ps1_responses_id_key ON public.ps1_responses USING btree (id);

CREATE UNIQUE INDEX ps1_responses_pkey ON public.ps1_responses USING btree (id);

CREATE UNIQUE INDEX ps1_reviews_pkey ON public.ps1_reviews USING btree (created_by, batch, station, review);

CREATE UNIQUE INDEX ps2_responses__pkey ON public.ps2_responses USING btree (id);

CREATE UNIQUE INDEX ps2_reviews_pkey ON public.ps2_reviews USING btree (created_by, batch, station, review);

CREATE UNIQUE INDEX rants_pkey ON public.rants USING btree (id);

CREATE UNIQUE INDEX resources_pkey ON public.resources USING btree (id);

CREATE UNIQUE INDEX reviews_pkey ON public.course_reviews USING btree (created_by, course, prof, review);

CREATE UNIQUE INDEX si_chronicles_pkey ON public.si_chronicles USING btree (name, company, year);

CREATE UNIQUE INDEX si_companies_pkey ON public.si_companies USING btree (name, year, roles);

alter table "public"."course_reviews" add constraint "reviews_pkey" PRIMARY KEY using index "reviews_pkey";

alter table "public"."ps1_responses" add constraint "ps1_responses_pkey" PRIMARY KEY using index "ps1_responses_pkey";

alter table "public"."ps1_reviews" add constraint "ps1_reviews_pkey" PRIMARY KEY using index "ps1_reviews_pkey";

alter table "public"."ps2_responses" add constraint "ps2_responses__pkey" PRIMARY KEY using index "ps2_responses__pkey";

alter table "public"."ps2_reviews" add constraint "ps2_reviews_pkey" PRIMARY KEY using index "ps2_reviews_pkey";

alter table "public"."rants" add constraint "rants_pkey" PRIMARY KEY using index "rants_pkey";

alter table "public"."resources" add constraint "resources_pkey" PRIMARY KEY using index "resources_pkey";

alter table "public"."si_chronicles" add constraint "si_chronicles_pkey" PRIMARY KEY using index "si_chronicles_pkey";

alter table "public"."si_companies" add constraint "si_companies_pkey" PRIMARY KEY using index "si_companies_pkey";

alter table "public"."course_reviews" add constraint "reviews_review_check" CHECK ((length(review) < 5000)) not valid;

alter table "public"."course_reviews" validate constraint "reviews_review_check";

alter table "public"."ps1_responses" add constraint "ps1_responses_id_key" UNIQUE using index "ps1_responses_id_key";

alter table "public"."ps1_reviews" add constraint "reviews_review_check" CHECK ((length(review) < 5000)) not valid;

alter table "public"."ps1_reviews" validate constraint "reviews_review_check";

alter table "public"."ps2_reviews" add constraint "reviews_review_check" CHECK ((length(review) < 5000)) not valid;

alter table "public"."ps2_reviews" validate constraint "reviews_review_check";

grant delete on table "public"."course_reviews" to "anon";

grant insert on table "public"."course_reviews" to "anon";

grant references on table "public"."course_reviews" to "anon";

grant select on table "public"."course_reviews" to "anon";

grant trigger on table "public"."course_reviews" to "anon";

grant truncate on table "public"."course_reviews" to "anon";

grant update on table "public"."course_reviews" to "anon";

grant delete on table "public"."course_reviews" to "authenticated";

grant insert on table "public"."course_reviews" to "authenticated";

grant references on table "public"."course_reviews" to "authenticated";

grant select on table "public"."course_reviews" to "authenticated";

grant trigger on table "public"."course_reviews" to "authenticated";

grant truncate on table "public"."course_reviews" to "authenticated";

grant update on table "public"."course_reviews" to "authenticated";

grant delete on table "public"."course_reviews" to "service_role";

grant insert on table "public"."course_reviews" to "service_role";

grant references on table "public"."course_reviews" to "service_role";

grant select on table "public"."course_reviews" to "service_role";

grant trigger on table "public"."course_reviews" to "service_role";

grant truncate on table "public"."course_reviews" to "service_role";

grant update on table "public"."course_reviews" to "service_role";

grant delete on table "public"."ps1_responses" to "anon";

grant insert on table "public"."ps1_responses" to "anon";

grant references on table "public"."ps1_responses" to "anon";

grant select on table "public"."ps1_responses" to "anon";

grant trigger on table "public"."ps1_responses" to "anon";

grant truncate on table "public"."ps1_responses" to "anon";

grant update on table "public"."ps1_responses" to "anon";

grant delete on table "public"."ps1_responses" to "authenticated";

grant insert on table "public"."ps1_responses" to "authenticated";

grant references on table "public"."ps1_responses" to "authenticated";

grant select on table "public"."ps1_responses" to "authenticated";

grant trigger on table "public"."ps1_responses" to "authenticated";

grant truncate on table "public"."ps1_responses" to "authenticated";

grant update on table "public"."ps1_responses" to "authenticated";

grant delete on table "public"."ps1_responses" to "service_role";

grant insert on table "public"."ps1_responses" to "service_role";

grant references on table "public"."ps1_responses" to "service_role";

grant select on table "public"."ps1_responses" to "service_role";

grant trigger on table "public"."ps1_responses" to "service_role";

grant truncate on table "public"."ps1_responses" to "service_role";

grant update on table "public"."ps1_responses" to "service_role";

grant delete on table "public"."ps1_reviews" to "anon";

grant insert on table "public"."ps1_reviews" to "anon";

grant references on table "public"."ps1_reviews" to "anon";

grant select on table "public"."ps1_reviews" to "anon";

grant trigger on table "public"."ps1_reviews" to "anon";

grant truncate on table "public"."ps1_reviews" to "anon";

grant update on table "public"."ps1_reviews" to "anon";

grant delete on table "public"."ps1_reviews" to "authenticated";

grant insert on table "public"."ps1_reviews" to "authenticated";

grant references on table "public"."ps1_reviews" to "authenticated";

grant select on table "public"."ps1_reviews" to "authenticated";

grant trigger on table "public"."ps1_reviews" to "authenticated";

grant truncate on table "public"."ps1_reviews" to "authenticated";

grant update on table "public"."ps1_reviews" to "authenticated";

grant delete on table "public"."ps1_reviews" to "service_role";

grant insert on table "public"."ps1_reviews" to "service_role";

grant references on table "public"."ps1_reviews" to "service_role";

grant select on table "public"."ps1_reviews" to "service_role";

grant trigger on table "public"."ps1_reviews" to "service_role";

grant truncate on table "public"."ps1_reviews" to "service_role";

grant update on table "public"."ps1_reviews" to "service_role";

grant delete on table "public"."ps2_responses" to "anon";

grant insert on table "public"."ps2_responses" to "anon";

grant references on table "public"."ps2_responses" to "anon";

grant select on table "public"."ps2_responses" to "anon";

grant trigger on table "public"."ps2_responses" to "anon";

grant truncate on table "public"."ps2_responses" to "anon";

grant update on table "public"."ps2_responses" to "anon";

grant delete on table "public"."ps2_responses" to "authenticated";

grant insert on table "public"."ps2_responses" to "authenticated";

grant references on table "public"."ps2_responses" to "authenticated";

grant select on table "public"."ps2_responses" to "authenticated";

grant trigger on table "public"."ps2_responses" to "authenticated";

grant truncate on table "public"."ps2_responses" to "authenticated";

grant update on table "public"."ps2_responses" to "authenticated";

grant delete on table "public"."ps2_responses" to "service_role";

grant insert on table "public"."ps2_responses" to "service_role";

grant references on table "public"."ps2_responses" to "service_role";

grant select on table "public"."ps2_responses" to "service_role";

grant trigger on table "public"."ps2_responses" to "service_role";

grant truncate on table "public"."ps2_responses" to "service_role";

grant update on table "public"."ps2_responses" to "service_role";

grant delete on table "public"."ps2_reviews" to "anon";

grant insert on table "public"."ps2_reviews" to "anon";

grant references on table "public"."ps2_reviews" to "anon";

grant select on table "public"."ps2_reviews" to "anon";

grant trigger on table "public"."ps2_reviews" to "anon";

grant truncate on table "public"."ps2_reviews" to "anon";

grant update on table "public"."ps2_reviews" to "anon";

grant delete on table "public"."ps2_reviews" to "authenticated";

grant insert on table "public"."ps2_reviews" to "authenticated";

grant references on table "public"."ps2_reviews" to "authenticated";

grant select on table "public"."ps2_reviews" to "authenticated";

grant trigger on table "public"."ps2_reviews" to "authenticated";

grant truncate on table "public"."ps2_reviews" to "authenticated";

grant update on table "public"."ps2_reviews" to "authenticated";

grant delete on table "public"."ps2_reviews" to "service_role";

grant insert on table "public"."ps2_reviews" to "service_role";

grant references on table "public"."ps2_reviews" to "service_role";

grant select on table "public"."ps2_reviews" to "service_role";

grant trigger on table "public"."ps2_reviews" to "service_role";

grant truncate on table "public"."ps2_reviews" to "service_role";

grant update on table "public"."ps2_reviews" to "service_role";

grant delete on table "public"."rants" to "anon";

grant insert on table "public"."rants" to "anon";

grant references on table "public"."rants" to "anon";

grant select on table "public"."rants" to "anon";

grant trigger on table "public"."rants" to "anon";

grant truncate on table "public"."rants" to "anon";

grant update on table "public"."rants" to "anon";

grant delete on table "public"."rants" to "authenticated";

grant insert on table "public"."rants" to "authenticated";

grant references on table "public"."rants" to "authenticated";

grant select on table "public"."rants" to "authenticated";

grant trigger on table "public"."rants" to "authenticated";

grant truncate on table "public"."rants" to "authenticated";

grant update on table "public"."rants" to "authenticated";

grant delete on table "public"."rants" to "service_role";

grant insert on table "public"."rants" to "service_role";

grant references on table "public"."rants" to "service_role";

grant select on table "public"."rants" to "service_role";

grant trigger on table "public"."rants" to "service_role";

grant truncate on table "public"."rants" to "service_role";

grant update on table "public"."rants" to "service_role";

grant delete on table "public"."resources" to "anon";

grant insert on table "public"."resources" to "anon";

grant references on table "public"."resources" to "anon";

grant select on table "public"."resources" to "anon";

grant trigger on table "public"."resources" to "anon";

grant truncate on table "public"."resources" to "anon";

grant update on table "public"."resources" to "anon";

grant delete on table "public"."resources" to "authenticated";

grant insert on table "public"."resources" to "authenticated";

grant references on table "public"."resources" to "authenticated";

grant select on table "public"."resources" to "authenticated";

grant trigger on table "public"."resources" to "authenticated";

grant truncate on table "public"."resources" to "authenticated";

grant update on table "public"."resources" to "authenticated";

grant delete on table "public"."resources" to "service_role";

grant insert on table "public"."resources" to "service_role";

grant references on table "public"."resources" to "service_role";

grant select on table "public"."resources" to "service_role";

grant trigger on table "public"."resources" to "service_role";

grant truncate on table "public"."resources" to "service_role";

grant update on table "public"."resources" to "service_role";

grant delete on table "public"."si_chronicles" to "anon";

grant insert on table "public"."si_chronicles" to "anon";

grant references on table "public"."si_chronicles" to "anon";

grant select on table "public"."si_chronicles" to "anon";

grant trigger on table "public"."si_chronicles" to "anon";

grant truncate on table "public"."si_chronicles" to "anon";

grant update on table "public"."si_chronicles" to "anon";

grant delete on table "public"."si_chronicles" to "authenticated";

grant insert on table "public"."si_chronicles" to "authenticated";

grant references on table "public"."si_chronicles" to "authenticated";

grant select on table "public"."si_chronicles" to "authenticated";

grant trigger on table "public"."si_chronicles" to "authenticated";

grant truncate on table "public"."si_chronicles" to "authenticated";

grant update on table "public"."si_chronicles" to "authenticated";

grant delete on table "public"."si_chronicles" to "service_role";

grant insert on table "public"."si_chronicles" to "service_role";

grant references on table "public"."si_chronicles" to "service_role";

grant select on table "public"."si_chronicles" to "service_role";

grant trigger on table "public"."si_chronicles" to "service_role";

grant truncate on table "public"."si_chronicles" to "service_role";

grant update on table "public"."si_chronicles" to "service_role";

grant delete on table "public"."si_companies" to "anon";

grant insert on table "public"."si_companies" to "anon";

grant references on table "public"."si_companies" to "anon";

grant select on table "public"."si_companies" to "anon";

grant trigger on table "public"."si_companies" to "anon";

grant truncate on table "public"."si_companies" to "anon";

grant update on table "public"."si_companies" to "anon";

grant delete on table "public"."si_companies" to "authenticated";

grant insert on table "public"."si_companies" to "authenticated";

grant references on table "public"."si_companies" to "authenticated";

grant select on table "public"."si_companies" to "authenticated";

grant trigger on table "public"."si_companies" to "authenticated";

grant truncate on table "public"."si_companies" to "authenticated";

grant update on table "public"."si_companies" to "authenticated";

grant delete on table "public"."si_companies" to "service_role";

grant insert on table "public"."si_companies" to "service_role";

grant references on table "public"."si_companies" to "service_role";

grant select on table "public"."si_companies" to "service_role";

grant trigger on table "public"."si_companies" to "service_role";

grant truncate on table "public"."si_companies" to "service_role";

grant update on table "public"."si_companies" to "service_role";

create policy "Enable insert for anyone"
on "public"."course_reviews"
as permissive
for insert
to authenticated, anon
with check (true);


create policy "Enable read access for all users"
on "public"."course_reviews"
as permissive
for select
to public
using (true);


create policy "Enable insert for anyone"
on "public"."ps1_responses"
as permissive
for insert
to authenticated, anon
with check (true);


create policy "Enable read access for all users"
on "public"."ps1_responses"
as permissive
for select
to public
using (true);


create policy "Enable insert for anyone"
on "public"."ps1_reviews"
as permissive
for insert
to anon
with check (true);


create policy "Enable read access for all users"
on "public"."ps1_reviews"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "public"."ps2_responses"
as permissive
for insert
to authenticated, anon
with check (true);


create policy "Enable read access for all users"
on "public"."ps2_responses"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "public"."ps2_reviews"
as permissive
for insert
to anon
with check (true);


create policy "Enable read access for all users"
on "public"."ps2_reviews"
as permissive
for select
to public
using (true);


create policy "Enable insert for everyone"
on "public"."rants"
as permissive
for insert
to authenticated, anon
with check (true);


create policy "Enable read access for all users"
on "public"."rants"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "public"."resources"
as permissive
for insert
to authenticated, anon
with check (true);


create policy "Enable read access for all users"
on "public"."resources"
as permissive
for select
to public
using (true);


create policy "Enable update access for all users"
on "public"."resources"
as permissive
for update
to anon
using (true);


create policy "Enable read access for all users"
on "public"."si_chronicles"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."si_companies"
as permissive
for select
to public
using (true);



